import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Download, Plus, ShieldCheck } from "lucide-react";
import { api, formatDateTime } from "../lib/api";
import { EmptyState, Field, Loading, Modal, Notice, PageHeader, SearchInput } from "../components/UI";

const emptyForm = { tipo: "robo", area: "piso_venta", gravedad: "media", asunto: "", descripcion: "", intervencion: false, detencion: false };
export default function IncidenciasSeguridad({ user, management = false }) {
  const [rows, setRows] = useState(null); const [open, setOpen] = useState(false); const [notice, setNotice] = useState(null); const [search, setSearch] = useState(""); const [state, setState] = useState("todos"); const [severity, setSeverity] = useState("todas"); const [form, setForm] = useState(emptyForm);
  const load = () => api("/incidencias").then(setRows).catch((e) => setNotice({ type: "error", text: e.message })); useEffect(() => { load(); }, []);
  const filtered = useMemo(() => (rows || []).filter((r) => `${r.codigo || ""} ${r.tipo || ""} ${r.asunto} ${r.descripcion}`.toLowerCase().includes(search.toLowerCase()) && (state === "todos" || (r.estado || "abierta") === state) && (severity === "todas" || r.gravedad === severity)), [rows, search, state, severity]);
  const openRows = (rows || []).filter((r) => (r.estado || "abierta") === "abierta"); const reviewRows = (rows || []).filter((r) => r.estado === "en_revision"); const closedRows = (rows || []).filter((r) => r.estado === "cerrada");
  const save = async (e) => { e.preventDefault(); try { const result = await api("/incidencias", { method: "POST", body: form }); setOpen(false); setForm(emptyForm); await load(); if (result.notificacion_estado !== "enviada") setNotice({ type: "error", text: `Incidencia guardada; correo ${result.notificacion_estado}.` }); } catch (error) { setNotice({ type: "error", text: error.message }); } };
  const exportCsv = () => downloadCsv("incidencias.csv", ["Código,Fecha,Tipo,Área,Severidad,Estado", ...filtered.map((r) => [r.codigo || `INC-${String(r.id).padStart(4, "0")}`, r.fecha, r.tipo || r.asunto, r.area || "", r.gravedad, r.estado || "abierta"].join(","))]);
  if (!rows) return <Loading />;
  return <>
    <PageHeader eyebrow={management ? "Operación de tienda" : "Seguridad"} title="Incidencias" subtitle="Registro y seguimiento de eventos operativos y de seguridad" action={<button className="button button--primary" onClick={() => setOpen(true)}><Plus size={16} /> Nueva incidencia</button>} />
    {notice && <Notice type={notice.type} onClose={() => setNotice(null)}>{notice.text}</Notice>}
    <div className="security-metrics security-metrics--traffic"><Metric title="Abiertas" value={openRows.length} tone="red" footer={`${openRows.filter((r) => ["alta", "critica"].includes(r.gravedad)).length} de alta severidad`} /><Metric title="En revisión" value={reviewRows.length} tone="amber" footer="Pendientes de validar" /><Metric title="Cerradas" value={closedRows.length} tone="green" footer="Histórico registrado" /></div>
    <section className="panel security-history"><div className="security-filter-grid"><SearchInput value={search} onChange={setSearch} placeholder="Código, tipo o detalle" /><select value={state} onChange={(e) => setState(e.target.value)}><option value="todos">Todos los estados</option><option value="abierta">Abiertas</option><option value="en_revision">En revisión</option><option value="cerrada">Cerradas</option></select><select value={severity} onChange={(e) => setSeverity(e.target.value)}><option value="todas">Todas las severidades</option><option value="baja">Baja</option><option value="media">Media</option><option value="alta">Alta</option><option value="critica">Crítica</option></select><button className="button button--ghost" onClick={exportCsv}><Download size={15} /> Exportar</button></div>{filtered.length ? <div className="security-table"><div className="security-table__head security-table__head--incidents"><span>Código</span><span>Fecha</span><span>Tipo</span><span>Área</span><span>Severidad</span><span>Estado</span></div>{filtered.map((r) => <div className="security-table__row security-table__row--incidents" key={r.id}><strong>{r.codigo || `INC-${String(r.id).padStart(4, "0")}`}</strong><span>{formatDateTime(r.fecha)}</span><span>{label(r.tipo) || r.asunto}</span><span>{label(r.area) || "—"}</span><span className={`security-pill security-pill--${r.gravedad}`}>{r.gravedad}</span><span className="security-pill">{label(r.estado) || "Abierta"}</span></div>)}</div> : <EmptyState icon={ShieldCheck} title="Sin incidencias" text="No hay resultados para los filtros seleccionados." />}</section>
    <Modal open={open} title="Nueva incidencia" subtitle="Registra la información principal del hecho" wide onClose={() => setOpen(false)}><form className="form-grid" onSubmit={save}><Field label="Tienda"><input disabled value={user?.tienda_nombre || "Tienda asignada automáticamente"} /></Field><Field label="Tipo de incidencia"><select value={form.tipo} onChange={(e) => setForm({ ...form, tipo: e.target.value })}><option value="robo">Robo</option><option value="robo_frustrado">Robo frustrado</option><option value="accidente">Accidente</option><option value="dano">Daño</option><option value="conflicto">Conflicto</option><option value="otro">Otro</option></select></Field><Field label="Área o ubicación"><select value={form.area} onChange={(e) => setForm({ ...form, area: e.target.value })}><option value="piso_venta">Piso de venta</option><option value="caja">Caja</option><option value="almacen">Almacén</option><option value="ingreso">Ingreso</option><option value="exterior">Exterior</option><option value="otro">Otro</option></select></Field><Field label="Severidad"><select value={form.gravedad} onChange={(e) => setForm({ ...form, gravedad: e.target.value })}><option value="baja">Baja</option><option value="media">Media</option><option value="alta">Alta</option><option value="critica">Crítica</option></select></Field><Field label="Asunto" className="span-2"><input required value={form.asunto} onChange={(e) => setForm({ ...form, asunto: e.target.value })} /></Field><Field label="Descripción del hecho" className="span-2" hint="Indica qué ocurrió, cómo se detectó y qué acciones iniciales se tomaron."><textarea required rows="5" value={form.descripcion} onChange={(e) => setForm({ ...form, descripcion: e.target.value })} /></Field><Field label="¿Hubo intervención?"><select value={form.intervencion ? "si" : "no"} onChange={(e) => setForm({ ...form, intervencion: e.target.value === "si" })}><option value="no">No</option><option value="si">Sí</option></select></Field><Field label="¿Hubo detención?"><select value={form.detencion ? "si" : "no"} onChange={(e) => setForm({ ...form, detencion: e.target.value === "si" })}><option value="no">No</option><option value="si">Sí</option></select></Field><div className="form-actions span-2"><button type="button" className="button button--ghost" onClick={() => setOpen(false)}>Cancelar</button><button className="button button--primary">Registrar y notificar</button></div></form></Modal>
  </>;
}
function Metric({ title, value, tone, footer }) { return <article className="security-metric"><span className={`security-metric__icon security-metric__icon--${tone}`}><AlertTriangle size={20} /></span><div><small>{title}</small><strong>{value}</strong><em className={`tone-${tone}`}>{footer}</em></div></article>; }
function label(v) { return v ? v.replaceAll("_", " ").replace(/^./, (c) => c.toUpperCase()) : ""; }
function downloadCsv(name, lines) { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([lines.join("\n")], { type: "text/csv;charset=utf-8" })); link.download = name; link.click(); URL.revokeObjectURL(link.href); }
