import MarketingStaffModal from "./MarketingStaffModal";
import { blankMarketingStaff } from "./marketingStaff";
import MarketingAttendance from "./MarketingAttendance";
import { useCallback, useEffect, useMemo, useState } from "react";
import { BarChart3, CalendarCheck2, Pencil, Trash2, ClipboardList, Megaphone, Plus, RefreshCw, TrendingUp, Users } from "lucide-react";
import { api, formatDate, todayISO } from "../lib/api";
import { ConfirmDialog, EmptyState, Field, Loading, Notice, PageHeader, StatusBadge } from "../components/UI";

const sections=[["inicio","Inicio"],["personal","Personal"],["asistencia","Asistencia"],["validacion","Validación"],["incidencias","Incidencias"],["capacitaciones","Capacitaciones"],["entregables","Resumen de entregables"],["campanas","Registro de campaña"],["amonestaciones","Amonestaciones"],["errores","Errores"],["seguidores","Seguidores por redes"]];
const roles=["coordinador_marketing","analista_marketing","disenador","community_manager","productor_contenido","promotor_marketing"];
const incidentTypes=["desembolso_presupuestal","incumplimiento_proveedores","incumplimiento_jefes_area","incumplimiento_caja","campana","informacion_dudosa","incumplimiento_tienda"];
const initial={staff:blankMarketingStaff,attendance:{personal_id:"",fecha:todayISO(),estado:"presente",observaciones:""},validation:{campana_id:"",descripcion:"",presupuesto:"",estado:"pendiente"},training:{titulo:"",descripcion:"",fecha:todayISO(),instructor:"",estado:"programada",personal_ids:[]},incident:{tipo:incidentTypes[0],tienda_id:"",campana_id:"",descripcion:"",estado:"abierta"},deliverable:{campana_id:"",nombre:"",responsable:"",fecha_entrega:"",estado:"pendiente"},campaign:{nombre:"",descripcion:"",fecha_inicio:todayISO(),fecha_fin:todayISO(),rubros:"",presupuesto_previsto:"",presupuesto_real:"",trabajadores_ids:[],tiendas_ids:[]},warning:{personal_id:"",tipo:"verbal",motivo:"",fecha:todayISO()},error:{personal_id:"",tipo:"contenido",error:"",fecha:todayISO()},follower:{red:"Instagram",fecha:todayISO(),cantidad:"",observaciones:""}};

export default function Marketing({section="inicio"}){
  const [data,setData]=useState(null),[notice,setNotice]=useState(null),[saving,setSaving]=useState(false),[forms,setForms]=useState(initial),[view,setView]=useState("lista"),[editing,setEditing]=useState(null),[deleting,setDeleting]=useState(null),[staffOpen,setStaffOpen]=useState(false);
  useEffect(()=>{setView(section==="asistencia"?"registro":"lista");setStaffOpen(false);setEditing(null);setForms(initial);},[section]);
  const load=useCallback(()=>api("/marketing").then(setData).catch(e=>setNotice({type:"error",text:e.message})),[]);useEffect(()=>{load();},[load]);
  const set=(name,key,value)=>setForms(current=>({...current,[name]:{...current[name],[key]:value}}));
  const submit=async(event,endpoint,name)=>{event.preventDefault();setSaving(true);setNotice(null);try{await api(`/marketing/${endpoint}${editing?`/${editing.id}`:""}`,{method:editing?"PUT":"POST",body:forms[name]});setForms(current=>({...current,[name]:initial[name]}));setEditing(null);setStaffOpen(false);setView("lista");setNotice({type:"success",text:"Registro guardado correctamente."});await load();}catch(e){setNotice({type:"error",text:e.message});}finally{setSaving(false);}};
  const staffAction=async(row,method,body)=>{setSaving(true);try{await api(`/marketing/staff/${row.id}`,{method,body});setDeleting(null);await load();setNotice({type:"success",text:"Personal actualizado correctamente."});}catch(e){setNotice({type:"error",text:e.message});}finally{setSaving(false);}};
  const actions=row=><div className="marketing-row-actions"><button className="button button--ghost button--small" disabled={saving} onClick={()=>{setForms(current=>({...current,staff:{...initial.staff,...row.perfil,...row,password:"",horarios:row.perfil?.horarios||initial.staff.horarios,telefono:row.telefono||"",email:row.email||""}}));setEditing(row);setStaffOpen(true);}}><Pencil size={14}/>Editar</button><button className="button button--ghost button--small" disabled={saving} onClick={()=>staffAction(row,"PATCH",{estado:row.estado==="activo"?"inactivo":"activo"})}>{row.estado==="activo"?"Desactivar":"Activar"}</button><button className="button button--ghost button--small" disabled={saving} onClick={()=>setDeleting(row)}><Trash2 size={14}/>Eliminar</button></div>;
  const metrics=useMemo(()=>{if(!data)return{};const present=data.attendance.filter(x=>["presente","tardanza"].includes(x.estado)).length;return{budget:data.campaigns.reduce((s,x)=>s+Number(x.presupuesto_real||0),0),campaigns:data.campaigns.length,people:data.people.filter(x=>x.estado==="activo").length,traffic:data.traffic.reduce((s,x)=>s+Number(x.cantidad||0),0),attendance:data.attendance.length?Math.round(present/data.attendance.length*100):0};},[data]);
  if(!data&&!notice)return <Loading/>;return <section className="marketing-page">{!(section==="asistencia"&&view==="registro")&&<PageHeader eyebrow="Gestión de Marketing" title={sections.find(x=>x[0]===section)?.[1]} subtitle="Equipo, campañas y operación exclusiva del área de Marketing." action={<div className="header-actions">{section==="personal"&&<button className="button button--primary" onClick={()=>{setEditing(null);setForms(current=>({...current,staff:{...blankMarketingStaff,fecha_ingreso:todayISO()}}));setNotice(null);setStaffOpen(true);}}><Plus size={15}/>Agregar personal</button>}<button className="button button--ghost" onClick={load}><RefreshCw size={15}/>Actualizar</button></div>}/>} {notice&&!staffOpen&&<Notice type={notice.type} onClose={()=>setNotice(null)}>{notice.text}</Notice>}{data&&section!=="inicio"&&section!=="personal"&&<div className="module-view-tabs" role="tablist" aria-label="Vistas de Marketing"><button role="tab" aria-selected={view==="lista"} className={view==="lista"?"active":""} onClick={()=>setView("lista")}>{section==="asistencia"?"Historial":"Lista"}</button><button role="tab" aria-selected={view==="registro"} className={view==="registro"?"active":""} onClick={()=>{setEditing(null);setForms(initial);setView("registro");}}>{section==="personal"?"Agregar personal":section==="asistencia"?"Registrar asistencia":"Registrar"}</button></div>}{data&&<Content key={section} view={view} actions={actions} load={load} section={section} data={data} forms={forms} set={set} submit={submit} saving={saving} metrics={metrics}/>}<MarketingStaffModal key={staffOpen ? "open" : "closed"} open={staffOpen} editing={forms.staff} setEditing={updater=>setForms(current=>({...current,staff:updater(current.staff)}))} roles={roles} saving={saving} onClose={()=>{setStaffOpen(false);setEditing(null);}} onSubmit={e=>submit(e,"staff","staff")} error={notice?.type==="error"?notice.text:null}/><ConfirmDialog open={!!deleting} title="Eliminar personal" message={`¿Eliminar a ${deleting?.nombres||""} ${deleting?.apellidos||""}? También se eliminarán sus asistencias, amonestaciones y errores asociados.`} busy={saving} onClose={()=>setDeleting(null)} onConfirm={()=>staffAction(deleting,"DELETE")}/></section>;
}

function Content({section,data,forms,set,submit,saving,metrics,view,actions,load}){
  const personOptions=<>{data.people.filter(x=>x.estado==="activo").map(x=><option key={x.id} value={x.id}>{x.nombres} {x.apellidos} · {human(x.rol)}</option>)}</>;
  if(section==="inicio")return <><div className="marketing-kpis"><Kpi icon={TrendingUp} label="Presupuesto ejecutado" value={money(metrics.budget)}/><Kpi icon={Megaphone} label="Campañas" value={metrics.campaigns}/><Kpi icon={Users} label="Personal activo" value={metrics.people}/><Kpi icon={BarChart3} label="Tráfico de tiendas" value={metrics.traffic}/></div><div className="marketing-grid"><SimpleList title="Campañas recientes" rows={data.campaigns.map(x=>[x.nombre,`${formatDate(x.fecha_inicio)} · ${money(x.presupuesto_previsto)}`])}/><SimpleList title="Resumen del área" rows={[["Asistencia del mes",`${metrics.attendance}%`],["Validaciones pendientes",data.validations.filter(x=>x.estado==="pendiente").length],["Entregables pendientes",data.deliverables.filter(x=>x.estado!=="entregado").length],["Incidencias abiertas",data.incidents.filter(x=>x.estado!=="cerrada").length]]}/></div></>;
  if(section==="personal")return <Table columns={["Personal","DNI","Rol","Ingreso","Estado","Acciones"]} rows={data.people.map(x=>[`${x.nombres} ${x.apellidos}`,x.dni,human(x.rol),formatDate(x.fecha_ingreso),<StatusBadge key={x.id} value={x.estado}/>,actions(x)])}/>;
  if(section==="asistencia")return view==="registro"?<MarketingAttendance data={data} load={load}/>:<Table visible={view==="lista"} columns={["Fecha","Personal","Estado","Observaciones"]} rows={data.attendance.map(x=>[formatDate(x.fecha),person(x.personal_marketing),human(x.estado),x.observaciones||"?"])}/>;
  if(section==="validacion")return <><Form visible={view==="registro"} title="Registrar validación de campaña" onSubmit={e=>submit(e,"validations","validation")} saving={saving}>{data.campaigns.length?<><CampaignSelect value={forms.validation.campana_id} onChange={v=>set("validation","campana_id",v)} campaigns={data.campaigns}/><Input label="Presupuesto validado" type="number" value={forms.validation.presupuesto} onChange={v=>set("validation","presupuesto",v)}/><Select label="Estado" value={forms.validation.estado} onChange={v=>set("validation","estado",v)} options={["pendiente","aprobada","observada","rechazada"]}/><Area label="Descripción" value={forms.validation.descripcion} onChange={v=>set("validation","descripcion",v)}/></>:<p className="form-note field--full">Primero crea una campaña en “Registro de campaña”. Luego aparecerá aquí en el selector.</p>}</Form><Table visible={view==="lista"} columns={["Campaña","Descripción","Presupuesto","Estado"]} rows={data.validations.map(x=>[x.campanas_marketing?.nombre,x.descripcion,money(x.presupuesto),x.estado])}/></>;
  if(section==="incidencias")return <><Form visible={view==="registro"} title="Registrar incidencia" onSubmit={e=>submit(e,"incidents","incident")} saving={saving}><Select label="Tipo" value={forms.incident.tipo} onChange={v=>set("incident","tipo",v)} options={incidentTypes}/><Field label="Tienda"><select value={forms.incident.tienda_id} onChange={e=>set("incident","tienda_id",e.target.value)}><option value="">General</option>{data.stores.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></Field><CampaignSelect required={false} value={forms.incident.campana_id} onChange={v=>set("incident","campana_id",v)} campaigns={data.campaigns}/><Area label="Descripción" value={forms.incident.descripcion} onChange={v=>set("incident","descripcion",v)}/></Form><Table visible={view==="lista"} columns={["Tipo","Tienda / campaña","Descripción","Estado"]} rows={data.incidents.map(x=>[human(x.tipo),x.tiendas?.nombre||x.campanas_marketing?.nombre||"General",x.descripcion,x.estado])}/></>;
  if(section==="capacitaciones")return <><Form visible={view==="registro"} title="Crear capacitación para Marketing" onSubmit={e=>submit(e,"trainings","training")} saving={saving}><Input label="Título" value={forms.training.titulo} onChange={v=>set("training","titulo",v)}/><Input label="Instructor" required={false} value={forms.training.instructor} onChange={v=>set("training","instructor",v)}/><Input label="Fecha" type="date" value={forms.training.fecha} onChange={v=>set("training","fecha",v)}/><Select label="Estado" value={forms.training.estado} onChange={v=>set("training","estado",v)} options={["programada","realizada","cancelada"]}/><Field label="Participantes" className="field--full"><select multiple value={forms.training.personal_ids.map(String)} onChange={e=>set("training","personal_ids",selected(e))}>{personOptions}</select></Field><Area label="Descripción" required={false} value={forms.training.descripcion} onChange={v=>set("training","descripcion",v)}/></Form><Table visible={view==="lista"} columns={["Capacitación","Fecha","Instructor","Participantes","Estado"]} rows={data.trainings.map(x=>[x.titulo,formatDate(x.fecha),x.instructor||"—",x.personal_ids?.length||0,x.estado])}/></>;
  if(section==="entregables")return <><Form visible={view==="registro"} title="Registrar entregable" onSubmit={e=>submit(e,"deliverables","deliverable")} saving={saving}><CampaignSelect required={false} value={forms.deliverable.campana_id} onChange={v=>set("deliverable","campana_id",v)} campaigns={data.campaigns}/><Input label="Entregable" value={forms.deliverable.nombre} onChange={v=>set("deliverable","nombre",v)}/><Input label="Responsable" required={false} value={forms.deliverable.responsable} onChange={v=>set("deliverable","responsable",v)}/><Input label="Fecha de entrega" required={false} type="date" value={forms.deliverable.fecha_entrega} onChange={v=>set("deliverable","fecha_entrega",v)}/></Form><Table visible={view==="lista"} columns={["Entregable","Campaña","Responsable","Fecha","Estado"]} rows={data.deliverables.map(x=>[x.nombre,x.campanas_marketing?.nombre||"General",x.responsable||"—",formatDate(x.fecha_entrega),x.estado])}/></>;
  if(section==="campanas")return <><Form visible={view==="registro"} title="Registrar campaña" onSubmit={e=>submit(e,"campaigns","campaign")} saving={saving}><Input label="Nombre" value={forms.campaign.nombre} onChange={v=>set("campaign","nombre",v)}/><Input label="Rubro" value={forms.campaign.rubros} onChange={v=>set("campaign","rubros",v)}/><Input label="Fecha de inicio" type="date" value={forms.campaign.fecha_inicio} onChange={v=>set("campaign","fecha_inicio",v)}/><Input label="Fecha final" type="date" value={forms.campaign.fecha_fin} onChange={v=>set("campaign","fecha_fin",v)}/><Input label="Presupuesto previsto" type="number" value={forms.campaign.presupuesto_previsto} onChange={v=>set("campaign","presupuesto_previsto",v)}/><Input label="Presupuesto real" required={false} type="number" value={forms.campaign.presupuesto_real} onChange={v=>set("campaign","presupuesto_real",v)}/><Field label="Personal de Marketing" className="field--full"><select multiple value={forms.campaign.trabajadores_ids.map(String)} onChange={e=>set("campaign","trabajadores_ids",selected(e))}>{personOptions}</select></Field><Field label="Tiendas" className="field--full"><select multiple value={forms.campaign.tiendas_ids.map(String)} onChange={e=>set("campaign","tiendas_ids",selected(e))}>{data.stores.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></Field><Area label="Descripción" required={false} value={forms.campaign.descripcion} onChange={v=>set("campaign","descripcion",v)}/></Form><Table visible={view==="lista"} columns={["Campaña","Fechas","Rubro","Previsto","Real"]} rows={data.campaigns.map(x=>[x.nombre,`${formatDate(x.fecha_inicio)} – ${formatDate(x.fecha_fin)}`,x.rubros,money(x.presupuesto_previsto),money(x.presupuesto_real)])}/></>;
  if(section==="amonestaciones")return <><Form visible={view==="registro"} title="Registrar amonestación de Marketing" onSubmit={e=>submit(e,"warnings","warning")} saving={saving}><PersonSelect value={forms.warning.personal_id} onChange={v=>set("warning","personal_id",v)} options={personOptions}/><Select label="Tipo" value={forms.warning.tipo} onChange={v=>set("warning","tipo",v)} options={["verbal","carta_amonestacion","memorandum"]}/><Input label="Fecha" type="date" value={forms.warning.fecha} onChange={v=>set("warning","fecha",v)}/><Area label="Motivo" value={forms.warning.motivo} onChange={v=>set("warning","motivo",v)}/></Form><Table visible={view==="lista"} columns={["Fecha","Personal","Tipo","Motivo"]} rows={data.warnings.map(x=>[formatDate(x.fecha),person(x.personal_marketing),human(x.tipo),x.motivo])}/></>;
  if(section==="errores")return <><Form visible={view==="registro"} title="Registrar error de Marketing" onSubmit={e=>submit(e,"errors","error")} saving={saving}><PersonSelect value={forms.error.personal_id} onChange={v=>set("error","personal_id",v)} options={personOptions}/><Select label="Tipo" value={forms.error.tipo} onChange={v=>set("error","tipo",v)} options={["contenido","liberado"]}/><Input label="Fecha" type="date" value={forms.error.fecha} onChange={v=>set("error","fecha",v)}/><Area label="Error" value={forms.error.error} onChange={v=>set("error","error",v)}/></Form><Table visible={view==="lista"} columns={["Fecha","Personal","Tipo","Error"]} rows={data.errors.map(x=>[formatDate(x.fecha),person(x.personal_marketing),human(x.tipo),x.error])}/></>;
  return <><Form visible={view==="registro"} title="Registrar seguidores por red" onSubmit={e=>submit(e,"followers","follower")} saving={saving}><Select label="Red" value={forms.follower.red} onChange={v=>set("follower","red",v)} options={["Instagram","Facebook","TikTok","YouTube","LinkedIn","X"]}/><Input label="Fecha" type="date" value={forms.follower.fecha} onChange={v=>set("follower","fecha",v)}/><Input label="Seguidores" type="number" value={forms.follower.cantidad} onChange={v=>set("follower","cantidad",v)}/><Input label="Observaciones" required={false} value={forms.follower.observaciones} onChange={v=>set("follower","observaciones",v)}/></Form><Table visible={view==="lista"} columns={["Red","Fecha","Seguidores","Observaciones"]} rows={data.followers.map(x=>[x.red,formatDate(x.fecha),Number(x.cantidad).toLocaleString("es-PE"),x.observaciones||"—"])}/></>;
}

function Form({title,onSubmit,saving,children,visible=true}){if(!visible)return null;return <form className="panel marketing-form" onSubmit={onSubmit}><header className="panel__header"><h2>{title}</h2></header><div className="form-grid">{children}</div><div className="form-actions"><button className="button button--primary" disabled={saving}><Plus size={15}/>{saving?"Guardando…":"Guardar registro"}</button></div></form>}
function Input({label,value,onChange,type="text",required=true}){return <Field label={label}><input required={required} type={type} min={type==="number"?0:undefined} value={value} onChange={e=>onChange(e.target.value)}/></Field>}
function Area({label,value,onChange,required=true}){return <Field label={label} className="field--full"><textarea required={required} value={value} onChange={e=>onChange(e.target.value)}/></Field>}
function Select({label,value,onChange,options}){return <Field label={label}><select required value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x} value={x}>{human(x)}</option>)}</select></Field>}
function PersonSelect({value,onChange,options}){return <Field label="Personal de Marketing"><select required value={value} onChange={e=>onChange(e.target.value)}><option value="">Selecciona</option>{options}</select></Field>}
function CampaignSelect({value,onChange,campaigns,required=true}){return <Field label="Campaña"><select required={required} value={value} onChange={e=>onChange(e.target.value)}><option value="">{required?"Selecciona una campaña":"General / sin campaña"}</option>{campaigns.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></Field>}
function Kpi({icon:Icon,label,value}){return <article className="metric-card"><span><Icon size={18}/></span><div><small>{label}</small><strong>{value}</strong></div></article>}
function Table({columns,rows,visible=true}){if(!visible)return null;return <section className="panel marketing-table-panel">{rows.length?<div className="marketing-table"><div className="marketing-table__head" style={{gridTemplateColumns:`repeat(${columns.length}, minmax(130px, 1fr))`}}>{columns.map(x=><strong key={x}>{x}</strong>)}</div>{rows.map((row,i)=><div className="marketing-table__row" style={{gridTemplateColumns:`repeat(${columns.length}, minmax(130px, 1fr))`}} key={i}>{row.map((x,j)=><span key={j}>{j===row.length-1&&["activo","pendiente","aprobada","abierta","en_proceso","cerrada","programada","realizada"].includes(x)?<StatusBadge value={x}/>:x??"—"}</span>)}</div>)}</div>:<EmptyState icon={ClipboardList} title="Sin registros" text="Todavía no existe información en esta sección."/>}</section>}
function SimpleList({title,rows}){return <section className="panel"><header className="panel__header"><h2>{title}</h2></header>{rows.length?rows.map((x,i)=><div className="marketing-list-row" key={i}><strong>{x[0]}</strong><span>{x[1]}</span></div>):<EmptyState icon={CalendarCheck2} title="Sin información" text="Aún no hay registros."/>}</section>}
const selected=e=>[...e.target.selectedOptions].map(x=>Number(x.value));const person=x=>x?`${x.nombres} ${x.apellidos}`:"—";const human=x=>String(x||"—").replaceAll("_"," ").replace(/^./,c=>c.toUpperCase());const money=x=>new Intl.NumberFormat("es-PE",{style:"currency",currency:"PEN"}).format(Number(x||0));
