import { useEffect, useMemo, useState } from "react";
import { Check, ClipboardCheck, FileText, Plus, ShieldCheck, Upload } from "lucide-react";
import { api, downloadFile, formatDate, todayISO } from "../lib/api";
import { EmptyState, Field, Loading, Modal, Notice, PageHeader, StatusBadge } from "../components/UI";

const DOCUMENTOS_POR_AREA = {
  "Municipalidad": ["Certificado de Defensa Civil", "Licencia de Funcionamiento"],
  "Contabilidad": ["Ficha RUC"],
  "Ingeniero eléctrico": ["Pozo a Tierra", "Plan de Contingencia y Seguridad", "Rociadores", "Sistema de alarma contra incendios"],
  "Proveedor": ["Láminas de seguridad"],
  "Ingeniero civil": ["Plano de evacuación", "Plano de señalización", "Plano de instalaciones eléctricas", "Plano de arquitectura", "Plano de ubicación"],
  "Correos especiales": ["Correo recibido"],
};
const AREAS_DOCUMENTOS = Object.keys(DOCUMENTOS_POR_AREA);
const AREAS_REQUERIMIENTOS = ["Operaciones","Sistemas","Marketing","Seguridad","Logística","Mantenimiento","Recursos Humanos","Otro"];
const tabs = [["resumen","Resumen"],["documentos","Documentos"],["operacion","Operación"],["seguimiento","Seguimiento"],["apoyos","Apoyo de seguridad"]];
const reportKindBySub = { municipal:"documentos", reclamaciones:"reclamaciones", acciones:"acciones", bitacora:"bitacora", requerimientos:"requerimientos", observaciones:"supervisiones", mejoras:"mejoras" };
const blank = (type) => ({
  documento: { area_documental:AREAS_DOCUMENTOS[0], responsables:[AREAS_DOCUMENTOS[0]], codigo:"", tipo_documento:DOCUMENTOS_POR_AREA[AREAS_DOCUMENTOS[0]][0], frecuencia_revision:"Anual", fecha_emision:"", fecha_vencimiento:"", estado:"vigente", archivo:null },
  apoyo: { nombres:"", apellidos:"", dni:"", telefono:"", fecha_inicio:todayISO(), fecha_fin:todayISO(), motivo:"", foto:null },
  reclamacion: { codigo_hoja:"", fecha:todayISO(), consumidor_nombre:"", consumidor_documento:"", consumidor_contacto:"", producto_servicio:"", monto:"", tipo:"reclamo", detalle:"", pedido_consumidor:"", observaciones_proveedor:"", acciones_adoptadas:"", fecha_respuesta:"", responsable:"", estado:"registrado", archivo:null },
  accion: { fecha:todayISO(), tipo:"marketing", responsable:"", accion:"", estado:"pendiente", objetivo:"", observacion:"", archivo:null },
  bitacora: { fecha:todayISO(), venta_dia:"", categoria:"operacion", evento:"", descripcion:"", archivo:null },
  requerimiento: { requerimiento:"", cantidad:"", areas_responsables:[], urgencia:"corto_plazo", fecha_inicio:todayISO(), fecha_fin_objetivo:"", estado:"pendiente", comentario:"", archivo:null },
  seguimiento_requerimiento: { requerimiento_id:null, comentario:"", estado:"en_proceso", archivo:null },
  mejora: { fecha:todayISO(), seccion:"", area:"", responsable:"", que_mejoro:"", como_se_hizo:"", estado:"registrada", resultado_beneficio:"", antes:null, despues:null },
  observacion: { accion_realizada:"", comentario:"", soporte_requerido:false, archivo:null },
}[type]);

const FileField = ({ label, onChange, accept=".pdf,image/*", capture }) => {
  const [fileName,setFileName] = useState("");
  return <Field label={label} className="file-field"><div className={`file-picker ${fileName?"has-file":""}`}><input type="file" accept={accept} capture={capture} onChange={(e) => { const file=e.target.files?.[0]||null; setFileName(file?.name||""); onChange(file); }}/><span className="file-picker__icon"><Upload size={17}/></span><span className="file-picker__copy"><strong>{fileName||"Seleccionar archivo"}</strong><small>{fileName?"Archivo listo para guardar":"PDF, JPG, PNG o WEBP · máximo 5 MB"}</small></span>{fileName&&<Check size={16}/>}</div></Field>;
};
const Text = ({ label, name, form, setForm, ...props }) => <Field label={label}><input {...props} value={form[name] ?? ""} onChange={(e) => setForm({ ...form, [name]: e.target.value })} /></Field>;
const Area = ({ label, name, form, setForm }) => <Field label={label}><textarea rows="3" value={form[name] ?? ""} onChange={(e) => setForm({ ...form, [name]: e.target.value })} /></Field>;
const Select = ({ label, name, form, setForm, options }) => <Field label={label}><select value={form[name]} onChange={(e) => setForm({ ...form, [name]: e.target.value })}>{options.map(([v,l]) => <option value={v} key={v}>{l}</option>)}</select></Field>;

export default function MiTiendaGestion() {
  const [data,setData] = useState(null), [tab,setTab] = useState("resumen"), [sub,setSub] = useState("municipal");
  const [modal,setModal] = useState(null), [form,setForm] = useState(null), [busy,setBusy] = useState(false), [error,setError] = useState("");
  const load = () => api("/mi-tienda-gestion").then(setData).catch((e) => setData({ error:e.message }));
  useEffect(() => { load(); }, []);
  const open = (type, values={}) => {
    setError(""); setModal(type);
    if (type !== "documento") { setForm({ ...blank(type), ...values }); return; }
    const area = AREAS_DOCUMENTOS.includes(values.area_documental) ? values.area_documental : AREAS_DOCUMENTOS.includes(values.responsables?.[0]) ? values.responsables[0] : AREAS_DOCUMENTOS[0];
    const documentos = DOCUMENTOS_POR_AREA[area];
    setForm({ ...blank(type), ...values, area_documental:area, responsables:[area], tipo_documento:documentos.includes(values.tipo_documento) ? values.tipo_documento : documentos[0] });
  };
  const upload = async (file, folder) => {
    if (!file) return null; if (file.size > 5*1024*1024) throw new Error("El archivo supera los 5 MB.");
    const base64 = await new Promise((resolve,reject) => { const reader=new FileReader(); reader.onload=()=>resolve(reader.result); reader.onerror=reject; reader.readAsDataURL(file); });
    return api("/mi-tienda-gestion/archivo", { method:"POST", body:{ nombre:file.name, mime:file.type, base64, carpeta:folder } });
  };
  const save = async () => {
    setBusy(true); setError("");
    try {
      let payload={...form}, endpoint=modal;
      if (form.archivo) { const f=await upload(form.archivo,modal); payload[["accion","bitacora","requerimiento","seguimiento_requerimiento"].includes(modal) ? "evidencia_path" : modal === "observacion" ? "evidencia_cierre_path" : "archivo_path"]=f.path; payload[["accion","bitacora","requerimiento","seguimiento_requerimiento"].includes(modal) ? "evidencia_nombre" : modal === "observacion" ? "evidencia_cierre_nombre" : "archivo_nombre"]=f.nombre; }
      if (modal === "mejora") { const [a,d]=await Promise.all([upload(form.antes,"mejoras"),upload(form.despues,"mejoras")]); if(a) Object.assign(payload,{foto_antes_path:a.path,foto_antes_nombre:a.nombre}); if(d) Object.assign(payload,{foto_despues_path:d.path,foto_despues_nombre:d.nombre}); }
      if (modal === "apoyo") { const photo=await upload(form.foto,"apoyos-seguridad-referencias"); if(!photo) throw new Error("La foto de referencia es obligatoria."); payload.foto_referencia_path=photo.path; }
      delete payload.archivo; delete payload.antes; delete payload.despues; delete payload.foto;
      if (modal === "observacion") endpoint=`observaciones/${form.id}`;
      else if (modal === "seguimiento_requerimiento") endpoint=`requerimientos/${form.requerimiento_id}/seguimiento`;
      else endpoint={documento:"documentos",reclamacion:"reclamaciones",accion:"acciones",bitacora:"bitacora",requerimiento:"requerimientos",mejora:"mejoras",apoyo:"apoyos-seguridad"}[modal] + (form.id ? `/${form.id}` : "");
      await api(`/mi-tienda-gestion/${endpoint}`, { method:form.id && modal!=="seguimiento_requerimiento" ? "PUT":"POST", body:payload }); setModal(null); await load();
    } catch(e) { setError(e.message); } finally { setBusy(false); }
  };
  const viewFile = async (path) => { const {url}=await api("/mi-tienda-gestion/archivo-url",{method:"POST",body:{path}}); window.open(url,"_blank","noopener,noreferrer"); };
  const currentRows = useMemo(() => data?.[sub === "municipal" ? "documentos" : sub] || [], [data,sub]);
  if (!data) return <Loading />;
  if (data.error) return <Notice type="error">{data.error}</Notice>;
  const t=data.tienda || {}, r=data.resumen || {};
  return <>
    <PageHeader eyebrow="Gestión de tienda" title="Mi tienda" subtitle="Documentación, operación y seguimiento en un solo espacio." />
    <div className="mini-tabs">{tabs.map(([id,label]) => <button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}</button>)}</div>

    {tab === "resumen" && <div className="store-module">
      <section className="panel store-block"><header><div><small>Datos principales</small><h2>{t.nombre}</h2></div><button className="button button--ghost" onClick={()=>open("datos",t)}>Editar datos</button></header><div className="store-data-grid">{[["Código",t.codigo],["Zona",t.zona],["Formato",t.formato],["Clúster",t.cluster],["Distrito",t.distrito],["Dirección",t.direccion],["Alquiler mensual",t.alquiler_mensual!=null?`S/ ${Number(t.alquiler_mensual).toLocaleString("es-PE",{minimumFractionDigits:2})}`:null],["Estado operativo",t.estado]].map(([l,v])=><div key={l}><small>{l}</small><strong>{v||"Sin registrar"}</strong></div>)}</div></section>
      <div className="store-summary-grid">{[["Documentos próximos a vencer",r.documentos_por_vencer],["Reclamos en atención",r.reclamos_en_atencion],["Observaciones zonales abiertas",r.observaciones_abiertas],["Próxima acción",r.proxima_accion?.accion||"Sin acciones"],["Última mejora",r.ultima_mejora?.que_mejoro||"Sin mejoras"],["Última bitácora",r.ultima_bitacora?.fecha?formatDate(r.ultima_bitacora.fecha):"Sin registros"]].map(([l,v])=><section className="panel mini-status" key={l}><small>{l}</small><strong>{v}</strong></section>)}</div>
    </div>}

    {tab === "documentos" && <ModuleTabs items={[["municipal","Documentación municipal"],["reclamaciones","Libro de reclamaciones"],["alertas","Configuración de alertas"]]} sub={sub} setSub={setSub} />}
    {tab === "operacion" && <ModuleTabs items={[["acciones","Acciones de tienda"],["bitacora","Bitácora diaria"],["requerimientos","Requerimientos de tienda"]]} sub={sub} setSub={setSub} />}
    {tab === "seguimiento" && <ModuleTabs items={[["observaciones","Observaciones zonales"],["mejoras","Mejora continua"]]} sub={sub} setSub={setSub} />}
    {tab === "apoyos" && <SecuritySupports rows={data.apoyos_seguridad||[]} open={open} reload={load} />}
    {sub === "alertas" && <DocumentAlertSettings documents={data.documentos || []} reload={load} />}
    {!['resumen','apoyos'].includes(tab) && sub !== "alertas" && <Records section={sub} rows={currentRows} open={open} viewFile={viewFile} exportRows={()=>downloadFile(`/api/reportes/${reportKindBySub[sub]}/export.xlsx`,`reporte-${reportKindBySub[sub]}.xlsx`)} />}

    <EditorModal type={modal} form={form} setForm={setForm} error={error} busy={busy} onClose={()=>setModal(null)} onSave={modal==="datos" ? async()=>{setBusy(true);try{await api("/mi-tienda-gestion/datos",{method:"PUT",body:form});setModal(null);await load();}catch(e){setError(e.message);}finally{setBusy(false);}} : save} />
  </>;
}

function ModuleTabs({items,sub,setSub}) { useEffect(()=>{ if(!items.some(([id])=>id===sub)) setSub(items[0][0]); },[items,sub,setSub]); return <div className="subsection-tabs">{items.map(([id,label])=><button key={id} className={sub===id?"active":""} onClick={()=>setSub(id)}>{label}</button>)}</div>; }

function DocumentAlertSettings({ documents, reload }) {
  const [days, setDays] = useState({}); const [saving, setSaving] = useState(null); const [error, setError] = useState("");
  useEffect(() => { setDays(Object.fromEntries(documents.map((document) => [document.id, String(document.dias_alerta || 30)]))); }, [documents]);
  const save = async (document) => {
    const dias_alerta = Number(days[document.id]);
    if (!Number.isInteger(dias_alerta) || dias_alerta < 1 || dias_alerta > 365) { setError("Ingresa entre 1 y 365 días."); return; }
    setSaving(document.id); setError("");
    try { await api(`/mi-tienda-gestion/documentos/${document.id}`, { method:"PUT", body:{ ...document, dias_alerta } }); await reload(); }
    catch (e) { setError(e.message); } finally { setSaving(null); }
  };
  return <section className="panel records-panel alert-settings"><header><div><small>Configuración</small><h2>Alertas de vencimiento</h2><p>Define con cuántos días de anticipación deseas recibir la alerta de cada documento.</p></div></header>{error&&<Notice type="error">{error}</Notice>}{!documents.length?<EmptyState icon={FileText} title="Sin documentos" text="Registra un documento para configurar su alerta."/>:<div className="alert-settings__list">{documents.map((document)=><article key={document.id}><div><strong>{document.tipo_documento}</strong><small>{document.area_responsable || "Sin área"} · Vence {formatDate(document.fecha_vencimiento)}</small></div><label><span>Avisar antes de</span><input type="number" min="1" max="365" value={days[document.id] ?? 30} onChange={(event)=>setDays({ ...days, [document.id]:event.target.value })}/><em>días</em></label><button className="button button--ghost" disabled={saving===document.id} onClick={()=>save(document)}>{saving===document.id?"Guardando…":"Guardar"}</button></article>)}</div>}</section>;
}

function SecuritySupports({rows,open,reload}) {
  const toggle=async(row)=>{await api(`/mi-tienda-gestion/apoyos-seguridad/${row.id}`,{method:"PUT",body:{activo:!row.activo}});await reload();};
  return <section className="panel records-panel security-supports"><header><div><small>Accesos temporales</small><h2>Apoyos de seguridad</h2><p>El apoyo ingresa con DNI y una foto de rostro durante el periodo autorizado.</p></div><button className="button button--primary" onClick={()=>open("apoyo")}><Plus size={15}/>Agregar apoyo</button></header>{!rows.length?<EmptyState icon={ShieldCheck} title="Sin apoyos registrados" text="Agrega un apoyo cuando el jefe de seguridad se ausente."/>:<div className="compact-record-list">{rows.map(row=><article key={row.id}><div><strong>{row.usuarios?.nombres} {row.usuarios?.apellidos}</strong><small>DNI {row.dni} · {formatDate(row.fecha_inicio)} al {formatDate(row.fecha_fin)}</small><small>{row.motivo||"Cobertura temporal de seguridad"}</small></div><StatusBadge value={row.activo?"activo":"inactivo"}/><div className="record-actions"><button onClick={()=>toggle(row)}>{row.activo?"Desactivar acceso":"Reactivar acceso"}</button></div></article>)}</div>}</section>;
}

function Records({section,rows,open,viewFile,exportRows}) {
  const config={municipal:["documento","Actualizar documento"],reclamaciones:["reclamacion","Registrar reclamación"],acciones:["accion","Nueva acción"],bitacora:["bitacora","Registrar día"],requerimientos:["requerimiento","Nuevo requerimiento"],observaciones:[null,null],mejoras:["mejora","Registrar mejora"]}[section] || [];
  const title={municipal:"Documentación municipal",reclamaciones:"Libro de reclamaciones",acciones:"Acciones de tienda",bitacora:"Bitácora diaria",requerimientos:"Requerimientos de tienda",observaciones:"Observaciones zonales",mejoras:"Mejora continua"}[section];
  const primary=(row)=>row.tipo_documento||row.codigo_hoja||row.accion||row.evento||row.requerimiento||row.area_item||row.que_mejoro;
  const secondary=(row)=>row.responsables?.join(" · ")||row.area_responsable||row.consumidor_nombre||row.responsable||row.categoria||row.areas_responsables?.join(" · ")||row.descripcion||row.area;
  const path=(row)=>row.archivo_path||row.evidencia_path||row.evidencia_inicial_path||row.foto_despues_path;
  return <section className="panel records-panel"><header><div><small>Subsección</small><h2>{title}</h2></div><div className="header-actions"><button className="button button--ghost" onClick={exportRows}>Descargar Excel</button>{config[0]&&<button className="button button--primary" onClick={()=>open(config[0])}><Plus size={15}/>{config[1]}</button>}</div></header>
    {!rows.length?<EmptyState icon={section==="municipal"?FileText:ClipboardCheck} title="Sin registros" text="Aún no hay información en esta subsección."/>:<div className="compact-record-list">{rows.map(row=><article className={section==="requerimientos"?"requirement-record":""} key={row.id}><div><strong>{section==="requerimientos"?`REQ-${String(row.id).padStart(4,"0")} · `:""}{primary(row)||"Registro"}</strong><small>{secondary(row)||"Sin detalle"} · {formatDate(row.fecha||row.fecha_inicio||row.fecha_vencimiento||row.created_at)}</small>{section==="requerimientos"&&row.fecha_fin_objetivo&&<small>Fecha objetivo: {formatDate(row.fecha_fin_objetivo)} · {row.urgencia?.replaceAll("_"," ")}</small>}</div><StatusBadge value={row.estado||row.prioridad}/><div className="record-actions">{path(row)&&<button onClick={()=>viewFile(path(row))}>Ver archivo</button>}{section==="municipal"&&<button onClick={()=>open("documento",{...row,archivo:null})}>Renovar / editar</button>}{section==="reclamaciones"&&<button onClick={()=>open("reclamacion",{...row,archivo:null})}>Actualizar estado</button>}{section==="bitacora"&&<button onClick={()=>open("bitacora",{...row,archivo:null})}>Editar</button>}{section==="requerimientos"&&<><button onClick={()=>open("requerimiento",{...row,archivo:null})}>Ver / actualizar</button><button onClick={()=>open("seguimiento_requerimiento",{...blank("seguimiento_requerimiento"),requerimiento_id:row.id,estado:row.estado})}>Seguimiento</button></>}{section==="observaciones"&&!(["levantada","en_validacion"].includes(row.estado))&&<button onClick={()=>open("observacion",{...blank("observacion"),id:row.id})}>Levantar</button>}</div>{section==="requerimientos"&&!!row.seguimientos?.length&&<div className="requirement-timeline">{row.seguimientos.map(item=><div key={item.id}><span>{formatDate(item.created_at)}</span><strong>{item.usuarios ? `${item.usuarios.nombres||""} ${item.usuarios.apellidos||""}`.trim() : "Usuario"}</strong><span>{item.comentario}</span><StatusBadge value={item.estado}/></div>)}</div>}</article>)}</div>}
  </section>;
}

function EditorModal({type,form,setForm,error,busy,onClose,onSave}) {
  if(!form) return null;
  const titles={datos:"Datos principales",documento:"Documento municipal",reclamacion:"Reclamación",accion:"Acción de tienda",bitacora:"Bitácora diaria",requerimiento:"Requerimiento de tienda",seguimiento_requerimiento:"Seguimiento del requerimiento",mejora:"Mejora continua",observacion:"Levantar observación",apoyo:"Nuevo apoyo de seguridad"};
  return <Modal open={!!type} wide title={titles[type]} subtitle={type==="requerimiento"?"Registra la necesidad y deriva su atención al área responsable.":type==="seguimiento_requerimiento"?"Añade una actualización al historial del requerimiento.":undefined} onClose={onClose}><div className={`form-grid ${type==="requerimiento"?"requirement-form":""}`}>{error&&<div className="span-2"><Notice type="error">{error}</Notice></div>}
    {type==="datos"&&<><div className="span-2"><Text label="Nombre de la tienda *" name="nombre" form={form} setForm={setForm} required/></div><Text label="Código" name="codigo" form={form} setForm={setForm} placeholder="Ej. LIM-001"/><Text label="Zona" name="zona" form={form} setForm={setForm} placeholder="Ej. Lima Norte"/><Text label="Formato" name="formato" form={form} setForm={setForm} placeholder="Ej. Tienda / módulo"/><Text label="Distrito" name="distrito" form={form} setForm={setForm} placeholder="Ej. Lima"/><div className="span-2"><Text label="Dirección" name="direccion" form={form} setForm={setForm} placeholder="Av., calle y número"/></div><Text type="number" min="0" step="0.01" label="Alquiler mensual (S/)" name="alquiler_mensual" form={form} setForm={setForm}/><Select label="Estado operativo *" name="estado" form={form} setForm={setForm} options={[["activo","Activo"],["inactivo","Inactivo"]]}/><div className="field span-2"><span>Clúster</span><input disabled value={form.cluster || "Sin clúster asignado"}/><small className="form-hint">La asignación de clúster se gestiona desde la administración central.</small></div></>}
    {type==="documento"&&<><Field label="Área responsable *"><select required value={form.area_documental} onChange={(e)=>{const area=e.target.value;setForm({...form,area_documental:area,responsables:[area],tipo_documento:DOCUMENTOS_POR_AREA[area][0]});}}>{AREAS_DOCUMENTOS.map(area=><option value={area} key={area}>{area}</option>)}</select></Field><Select label="Documento *" name="tipo_documento" form={form} setForm={setForm} options={(DOCUMENTOS_POR_AREA[form.area_documental]||[]).map(documento=>[documento,documento])}/><Text label="Código" name="codigo" form={form} setForm={setForm}/><Text label="Frecuencia de revisión" name="frecuencia_revision" form={form} setForm={setForm}/><Text type="date" label="Fecha de emisión" name="fecha_emision" form={form} setForm={setForm}/><Text type="date" label="Fecha de vencimiento" name="fecha_vencimiento" form={form} setForm={setForm}/><Select label="Estado" name="estado" form={form} setForm={setForm} options={[["vigente","Vigente"],["por_vencer","Por vencer"],["vencido","Vencido"],["en_renovacion","En renovación"]]}/><FileField label="PDF o imagen" onChange={archivo=>setForm({...form,archivo})}/></>}
    {type==="apoyo"&&<><Text label="Nombres *" name="nombres" form={form} setForm={setForm}/><Text label="Apellidos *" name="apellidos" form={form} setForm={setForm}/><Text label="DNI *" name="dni" form={form} setForm={setForm} inputMode="numeric" maxLength="8"/><Text label="Celular" name="telefono" form={form} setForm={setForm} inputMode="numeric" maxLength="9"/><Text type="date" label="Inicio de autorización *" name="fecha_inicio" form={form} setForm={setForm}/><Text type="date" label="Fin de autorización *" name="fecha_fin" form={form} setForm={setForm}/><div className="span-2"><Area label="Motivo de la cobertura" name="motivo" form={form} setForm={setForm}/></div><div className="span-2"><FileField label="Foto de rostro de referencia *" accept="image/*" capture="user" onChange={foto=>setForm({...form,foto})}/><div className="form-hint">El apoyo ingresará desde la pantalla principal con su DNI y deberá tomar una nueva foto en cada acceso.</div></div></>}
    {type==="reclamacion"&&<><Text label="Código de hoja *" name="codigo_hoja" form={form} setForm={setForm}/><Text type="date" label="Fecha *" name="fecha" form={form} setForm={setForm}/><Text label="Consumidor *" name="consumidor_nombre" form={form} setForm={setForm}/><Text label="Documento" name="consumidor_documento" form={form} setForm={setForm}/><Text label="Contacto" name="consumidor_contacto" form={form} setForm={setForm}/><Text label="Producto / servicio *" name="producto_servicio" form={form} setForm={setForm}/><Text type="number" label="Monto reclamado" name="monto" form={form} setForm={setForm}/><Select label="Tipo" name="tipo" form={form} setForm={setForm} options={[["reclamo","Reclamo"],["queja","Queja"]]}/><Select label="Estado *" name="estado" form={form} setForm={setForm} options={[["registrado","Registrado"],["en_atencion","En atención"],["respondido","Respondido"],["cerrado","Cerrado"]]}/><Area label="Detalle *" name="detalle" form={form} setForm={setForm}/><Area label="Pedido del consumidor" name="pedido_consumidor" form={form} setForm={setForm}/><Area label="Observaciones del proveedor" name="observaciones_proveedor" form={form} setForm={setForm}/><Area label="Acciones adoptadas" name="acciones_adoptadas" form={form} setForm={setForm}/><Text type="date" label="Fecha de respuesta" name="fecha_respuesta" form={form} setForm={setForm}/><Text label="Responsable" name="responsable" form={form} setForm={setForm}/><FileField label="Documento / evidencia" onChange={archivo=>setForm({...form,archivo})}/></>}
    {type==="accion"&&<><Text type="date" label="Fecha *" name="fecha" form={form} setForm={setForm}/><Select label="Tipo" name="tipo" form={form} setForm={setForm} options={["marketing","promocion","activacion","volanteo","remarketing","exhibicion","reunion","operacion","otro"].map(x=>[x,x])}/><Text label="Responsable *" name="responsable" form={form} setForm={setForm}/><Text label="Acción *" name="accion" form={form} setForm={setForm}/><Select label="Estado" name="estado" form={form} setForm={setForm} options={[["pendiente","Pendiente"],["en_progreso","En progreso"],["completada","Completada"],["cancelada","Cancelada"]]}/><Area label="Objetivo / descripción" name="objetivo" form={form} setForm={setForm}/><Area label="Observación" name="observacion" form={form} setForm={setForm}/><FileField label="Evidencia" onChange={archivo=>setForm({...form,archivo})}/></>}
    {type==="bitacora"&&<><Text type="date" label="Fecha *" name="fecha" form={form} setForm={setForm}/><Text type="number" label="Venta del día *" name="venta_dia" form={form} setForm={setForm}/><Text label="Categoría *" name="categoria" form={form} setForm={setForm}/><Text label="Evento / nota" name="evento" form={form} setForm={setForm}/><Area label="Descripción" name="descripcion" form={form} setForm={setForm}/><FileField label="Evidencia / referencia" onChange={archivo=>setForm({...form,archivo})}/><div className="span-2 form-hint">El tráfico se obtiene automáticamente de los registros de Seguridad para la fecha elegida.</div></>}
    {type==="requerimiento"&&<><div className="span-2"><Text label="Requerimiento / necesidad *" name="requerimiento" form={form} setForm={setForm} placeholder="Describe de forma breve lo que necesita la tienda"/></div><Text type="number" min="0" step="1" label="Cantidad / unidades" name="cantidad" form={form} setForm={setForm} placeholder="Ej. 2"/><Select label="Urgencia *" name="urgencia" form={form} setForm={setForm} options={[["urgente","Urgente"],["corto_plazo","Corto plazo"],["mediano_plazo","Mediano plazo"],["largo_plazo","Largo plazo"]]}/><div className="field span-2"><span>Áreas responsables *</span><div className="requirement-areas">{AREAS_REQUERIMIENTOS.map(area=>{const selected=form.areas_responsables?.includes(area);return <button type="button" className={selected?"selected":""} aria-pressed={selected} key={area} onClick={()=>setForm({...form,areas_responsables:selected?(form.areas_responsables||[]).filter(x=>x!==area):[...(form.areas_responsables||[]),area]})}><i>{selected&&<Check size={12}/>}</i><span>{area}</span></button>})}</div></div><Text type="date" label="Fecha de inicio *" name="fecha_inicio" form={form} setForm={setForm}/><Text type="date" label="Fecha fin objetivo" name="fecha_fin_objetivo" form={form} setForm={setForm}/><Select label="Estado" name="estado" form={form} setForm={setForm} options={[["pendiente","Pendiente"],["en_proceso","En proceso"],["atendido","Atendido"],["cancelado","Cancelado"]]}/><FileField label="Evidencia inicial" onChange={archivo=>setForm({...form,archivo})}/><div className="span-2"><Area label="Comentario adicional" name="comentario" form={form} setForm={setForm}/></div></>}
    {type==="seguimiento_requerimiento"&&<><Select label="Estado *" name="estado" form={form} setForm={setForm} options={[["pendiente","Pendiente"],["en_proceso","En proceso"],["atendido","Atendido"],["cancelado","Cancelado"]]}/><FileField label="Evidencia" onChange={archivo=>setForm({...form,archivo})}/><div className="span-2"><Area label="Comentario *" name="comentario" form={form} setForm={setForm}/></div></>}
    {type==="mejora"&&<><Text type="date" label="Fecha *" name="fecha" form={form} setForm={setForm}/><Text label="Sección *" name="seccion" form={form} setForm={setForm}/><Select label="Área *" name="area" form={form} setForm={setForm} options={[["","Seleccionar área"],...AREAS_REQUERIMIENTOS.map(area=>[area,area]) ]}/><Text label="Responsable *" name="responsable" form={form} setForm={setForm}/><Area label="¿Qué se mejoró? *" name="que_mejoro" form={form} setForm={setForm}/><Area label="¿Cómo se hizo? *" name="como_se_hizo" form={form} setForm={setForm}/><FileField label="Foto antes" accept="image/*" onChange={antes=>setForm({...form,antes})}/><FileField label="Foto después" accept="image/*" onChange={despues=>setForm({...form,despues})}/><Select label="Estado" name="estado" form={form} setForm={setForm} options={[["registrada","Registrada"],["en_progreso","En progreso"],["completada","Completada"]]}/><Area label="Resultado / beneficio" name="resultado_beneficio" form={form} setForm={setForm}/></>}
    {type==="observacion"&&<><Area label="Acción correctiva realizada *" name="accion_realizada" form={form} setForm={setForm}/><Area label="Comentario" name="comentario" form={form} setForm={setForm}/><FileField label="Evidencia" onChange={archivo=>setForm({...form,archivo})}/><Field label="Soporte requerido"><label className="check-line"><input type="checkbox" checked={form.soporte_requerido} onChange={e=>setForm({...form,soporte_requerido:e.target.checked})}/> Sí, necesito soporte</label></Field></>}
    <div className="form-actions span-2"><button className="button button--ghost" onClick={onClose}>Cancelar</button><button className="button button--primary" disabled={busy} onClick={onSave}><Upload size={15}/>{busy?"Guardando…":"Guardar"}</button></div>
  </div></Modal>;
}
