import { useEffect, useState } from "react";
import { AlertTriangle, CalendarCheck2, FileClock, GraduationCap, Store, Users } from "lucide-react";
import { api, formatDate } from "../lib/api";
import { Loading, Notice, PageHeader, StatusBadge } from "../components/UI";

export default function MiTienda({ user, onNavigate }) {
  const [profile, setProfile] = useState(null); const [summary, setSummary] = useState(null); const [people, setPeople] = useState([]); const [documents, setDocuments] = useState([]); const [notice, setNotice] = useState(null);
  useEffect(() => { Promise.all([api("/perfil"), api("/operaciones/resumen"), api("/usuarios"), api("/documentos-tienda").catch(() => [])]).then(([p, s, team, docs]) => { setProfile(p); setSummary(s); setPeople(team); setDocuments(docs); }).catch((e) => setNotice({ type: "error", text: e.message })); }, []);
  if (!profile || !summary) return <Loading />;
  const storeName = profile.tienda_nombre || "Tienda asignada"; const expiring = documents.filter((d) => d.fecha_vencimiento && daysUntil(d.fecha_vencimiento) <= 30).slice(0, 4);
  const exportSummary = () => { const lines = ["Indicador,Valor", `Tienda,${storeName}`, `Personal activo,${people.filter((p) => p.estado === "activo").length}`, `Incidencias,${summary.incidencias}`, `Amonestaciones,${summary.amonestaciones}`, `Errores,${summary.errores}`, `Documentos por vencer,${summary.documentos_por_vencer}`]; const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([lines.join("\n")], { type: "text/csv;charset=utf-8" })); a.download = `resumen-${storeName}.csv`; a.click(); URL.revokeObjectURL(a.href); };
  return <>
    <PageHeader eyebrow="Administración de tienda" title="Inicio" subtitle={`Vista general de ${storeName}`} action={<button className="button button--ghost" onClick={exportSummary}>Exportar resumen</button>} />
    {notice && <Notice type={notice.type}>{notice.text}</Notice>}
    <div className="store-overview-grid"><section className="panel store-main-data"><header className="panel__header"><div><h2>Datos principales</h2><p>Información operativa de la sede</p></div><Store size={22} /></header><dl><div><dt>Nombre</dt><dd>{storeName}</dd></div><div><dt>Estado operativo</dt><dd><StatusBadge value="activo" /></dd></div><div className="span-2"><dt>Dirección</dt><dd>{profile.tienda_direccion || "Sin dirección registrada"}</dd></div><div><dt>Jefe responsable</dt><dd>{user.rol === "jefe_tienda" ? `${user.nombres} ${user.apellidos}` : "Jefe de tienda asignado"}</dd></div><div><dt>Personal activo</dt><dd>{people.filter((p) => p.estado === "activo").length}</dd></div></dl></section><div className="store-side-stack"><section className="panel"><header className="panel__header"><h2>Estado documental</h2></header>{user.rol === "jefe_tienda" ? expiring.length ? expiring.map((d) => <div className="store-doc-row" key={d.id}><div><strong>{d.nombre}</strong><small>Vence {formatDate(d.fecha_vencimiento)}</small></div><span className={daysUntil(d.fecha_vencimiento) <= 7 ? "danger-text" : ""}>{daysUntil(d.fecha_vencimiento)} días</span></div>) : <p className="store-empty-copy">Sin documentos próximos a vencer.</p> : <p className="store-empty-copy">Consulta disponible para el jefe de tienda.</p>}</section><section className="panel"><header className="panel__header"><h2>Accesos rápidos</h2></header><Quick icon={Users} text="Gestionar personal" action={() => onNavigate("usuarios")} /><Quick icon={CalendarCheck2} text="Registrar asistencia" action={() => onNavigate("asistencias")} /><Quick icon={GraduationCap} text="Revisar capacitaciones" action={() => onNavigate("capacitaciones")} /><Quick icon={AlertTriangle} text="Ver incidencias" action={() => onNavigate("incidencias-tienda")} /></section></div></div>
    <div className="security-metrics store-summary-metrics"><Mini icon={Users} label="Personal" value={people.length} /><Mini icon={AlertTriangle} label="Incidencias" value={summary.incidencias} /><Mini icon={FileClock} label="Documentos por vencer" value={summary.documentos_por_vencer} /></div>
  </>;
}
function Quick({ icon: Icon, text, action }) { return <button className="store-quick-row" onClick={action}><Icon size={16} /><span>{text}</span><strong>Ir</strong></button>; }
function Mini({ icon: Icon, label, value }) { return <article className="security-metric"><span className="security-metric__icon security-metric__icon--amber"><Icon size={19} /></span><div><small>{label}</small><strong>{value}</strong></div></article>; }
function daysUntil(value) { return Math.ceil((new Date(`${value}T12:00:00`) - new Date()) / 86400000); }
