import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, ShieldAlert, UsersRound } from "lucide-react";
import { api, todayISO } from "../lib/api";
import { Loading, Notice, PageHeader, StatusBadge } from "../components/UI";

export default function SeguridadInicio({ onNavigate }) {
  const [data, setData] = useState(null); const [error, setError] = useState("");
  useEffect(() => { Promise.all([api("/trafico"), api("/incidentes")]).then(([trafico, incidentes]) => setData({ trafico, incidentes })).catch((e) => setError(e.message)); }, []);
  if (error) return <Notice type="error">{error}</Notice>; if (!data) return <Loading />;
  const today = data.trafico.find((x) => x.fecha === todayISO()); const open = data.incidentes.filter((x) => x.estado === "abierta"); const pending = data.incidentes.filter((x) => ["revision", "borrador"].includes(x.estado));
  return <><PageHeader eyebrow="Seguridad" title="Inicio" subtitle="Resumen diario de tráfico e incidencias de tu tienda." /><section className="compact-metrics security-metrics"><div><UsersRound /><span>Tráfico hoy</span><strong>{today?.visitantes ?? "—"}</strong><small>{today ? `Registrado · ${String(today.hora).slice(0,5)}` : "Sin registrar"}</small></div><div><ShieldAlert /><span>Incidencias abiertas</span><strong>{open.length}</strong><small>Requieren seguimiento</small></div><div><AlertTriangle /><span>Pendientes</span><strong>{pending.length}</strong><small>Acción requerida</small></div></section><div className="security-home-grid"><section className="panel"><header className="panel__header"><div><h2>Pendientes del día</h2><p>Acciones prioritarias</p></div></header><div className="security-pending">{today ? <button onClick={() => onNavigate("trafico")}><CheckCircle2 /><span><strong>Tráfico registrado</strong><small>{today.visitantes} visitantes</small></span></button> : <button onClick={() => onNavigate("trafico")}><AlertTriangle /><span><strong>Registrar tráfico</strong><small>Falta el conteo de hoy</small></span></button>}{[...open, ...pending].slice(0,3).map((item) => <button key={item.id} onClick={() => onNavigate("incidentes")}><ShieldAlert /><span><strong>{item.codigo} · {item.tipo}</strong><small>{item.descripcion}</small></span><StatusBadge value={item.estado} /></button>)}</div></section><section className="panel"><header className="panel__header"><div><h2>Actividad reciente</h2><p>Últimos movimientos</p></div></header><div className="activity-list">{data.incidentes.slice(0,5).map((item) => <div key={item.id}><strong>{item.codigo}</strong><span>{item.tipo} · {item.fecha}</span></div>)}</div></section></div></>;
}
