import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, CalendarCheck2, CheckCircle2, ClipboardCheck, Download, Pencil, Plus, Search, UsersRound } from "lucide-react";
import { api, downloadFile, formatDate, formatDateTime, todayISO } from "../lib/api";
import { EmptyState, Field, Loading, Modal, Notice, PageHeader, StatusBadge } from "../components/UI";

const labels = {
  personal: ["Administradores de tienda", "Crea y consulta únicamente a los administradores de las tiendas de tu zona."],
  asistencia: ["Asistencia", "Cumplimiento diario, faltas, tardanzas y hora del último envío por tienda."],
  tareas: ["Cronogramas y tareas", "Asigna responsables y fechas límite, y controla el cumplimiento."],
  supervisiones: ["Supervisiones", "Registra visitas, checklists, observaciones, hallazgos y acciones correctivas."],
  incidencias: ["Incidencias", "Incidencias entre tiendas, externas o que afectan varias sedes de tu zona."],
};
const incidentTypes=[["diferencia_transferencia","Diferencia en transferencia"],["coordinacion_tiendas","Coordinación entre tiendas"],["apoyo_tiendas","Apoyo entre tiendas"],["logistica_externa","Logística externa"],["proveedor","Proveedor"],["infraestructura_externa","Infraestructura externa"],["otro","Otro"]];
const incidentScopes=[["entre_tiendas","Entre tiendas"],["externa_tienda","Externa a tienda"],["varias_tiendas","Afecta varias tiendas"]];
const labelOption=(options,value)=>options.find(([key])=>key===value)?.[1]||value;

export default function ZonalModule({ section, user }) {
  const [data, setData] = useState(null); const [stores, setStores] = useState([]); const [notice, setNotice] = useState(null); const [search, setSearch] = useState(""); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState(blank(section));
  const load = useCallback(() => { setData(null); setNotice(null); api(`/zonal/${section}`).then(setData).catch((error) => { setNotice({ type: "error", text: error.message }); setData(section === "asistencia" ? { fecha:todayISO(), tiendas:[] } : section === "supervisiones" ? { visitas:[], observaciones:[] } : []); }); }, [section]);
  useEffect(() => { load(); if (["tareas", "supervisiones", "incidencias"].includes(section)) api("/tiendas").then(setStores).catch(() => setStores([])); }, [load, section]);
  const create = async (event) => { event.preventDefault(); setBusy(true); try { let endpoint=`/zonal/${section}`; let body=form; let method="POST"; if(section==="personal"){endpoint=form.id?`/zonal/administradores/${form.id}`:"/usuarios";method=form.id?"PUT":"POST";body={...form,rol:"jefe_tienda",tienda_id:form.tienda_id||null,estado:form.estado||"activo",fecha_salida:""};} if(section==="incidencias"&&form.evidencia){const file=form.evidencia;if(file.size>5*1024*1024)throw new Error("La evidencia supera los 5 MB.");const evidencia_base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});body={...form,evidencia_base64,evidencia_mime:file.type,evidencia_nombre:file.name};delete body.evidencia;} await api(endpoint, { method, body }); setNotice({type:"success",text:section==="personal"&&form.id?"Administrador actualizado correctamente.":"Registro guardado correctamente."}); setOpen(false); setForm(blank(section)); await load(); } catch (error) { setNotice({ type: "error", text: error.message }); } finally { setBusy(false); } };
  const editAdministrator=(row)=>{setForm({...blank("personal"),...row,password:"",tienda_id:row.tienda_id||"",estado:row.estado||"activo"});setOpen(true);};
  const changeTask = async (id, estado) => { try { await api(`/zonal/tareas/${id}`, { method: "PUT", body: { estado } }); await load(); } catch (error) { setNotice({ type: "error", text: error.message }); } };
  const changeIncident = async (id, estado) => { try { await api(`/zonal/incidencias/${id}`, { method: "PUT", body: { estado } }); await load(); } catch (error) { setNotice({ type: "error", text: error.message }); } };
  const title = labels[section] || ["Resumen zonal", ""];
  return <>
    <PageHeader eyebrow={user?.rol === "gerencia_general" ? "Gerencia general" : "Jefe zonal"} title={title[0]} subtitle={user?.rol === "gerencia_general" && section === "supervisiones" ? "Consulta las visitas, resultados y hallazgos de todas las tiendas." : title[1]} action={user?.rol === "jefe_zonal" && ["personal","tareas","supervisiones","incidencias"].includes(section) && <div className="header-actions">{section==="incidencias"&&<button className="button button--ghost" onClick={()=>downloadFile("/api/zonal/incidencias/export.xlsx","incidencias-zonales.xlsx")}><Download size={16}/>Descargar Excel</button>}<button className="button button--primary" onClick={() => { setForm(blank(section)); setOpen(true); }}><Plus size={16} />{section==="personal"?"Nuevo administrador":section==="incidencias"?"Nueva incidencia zonal":"Nuevo registro"}</button></div>} />
    {notice && <Notice type={notice.type} onClose={() => setNotice(null)}>{notice.text}</Notice>}
    {!["asistencia","supervisiones"].includes(section) && <label className="search-box"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar…" /></label>}
    {!data ? <Loading /> : <Content section={section} data={data} search={search} setSearch={setSearch} changeTask={changeTask} changeIncident={changeIncident} editAdministrator={editAdministrator} />}
    <Modal open={open} wide title={section === "tareas" ? "Nueva tarea zonal" : section==="personal"?(form.id?"Editar administrador de tienda":"Nuevo administrador de tienda"):section==="incidencias"?"Nueva incidencia zonal":"Nueva supervisión"} onClose={() => setOpen(false)}>
      <form className="form-grid" onSubmit={create}>
        {["tareas","supervisiones"].includes(section)&&<Field label="Tienda"><select required value={form.tienda_id} onChange={(e) => setForm({ ...form, tienda_id: e.target.value })}><option value="">Selecciona</option>{stores.map((store) => <option key={store.id} value={store.id}>{store.nombre}</option>)}</select></Field>}
        {section === "personal" ? <AdministratorFields form={form} setForm={setForm}/> : section === "incidencias" ? <IncidentFields form={form} setForm={setForm} stores={stores}/> : section === "tareas" ? <TaskFields form={form} setForm={setForm} /> : <SupervisionFields form={form} setForm={setForm} />}
        <div className="form-actions span-2"><button type="button" className="button button--ghost" onClick={() => setOpen(false)}>Cancelar</button><button className="button button--primary" disabled={busy}>{busy ? "Guardando…" : "Guardar"}</button></div>
      </form>
    </Modal>
  </>;
}

function Content({ section, data, search, setSearch, changeTask, changeIncident, editAdministrator }) {
  if (section === "asistencia") return data.tiendas.length ? <div className="cards-list">{data.tiendas.map((row) => <article className="task-catalog-card" key={row.id}><span className="catalog-icon"><CalendarCheck2 size={18} /></span><div><strong>{row.nombre}</strong><span>{row.registrados}/{row.personal} registrados · {row.faltas} faltas · {row.tardanzas} tardanzas · {row.pendientes} pendientes</span></div><StatusBadge value={row.pendientes ? "pendiente" : "completado"} /><small>{row.ultimo_envio ? formatDateTime(row.ultimo_envio) : "Sin envío"}</small></article>)}</div> : <Empty icon={CalendarCheck2} title="Sin tiendas" />;
  if (section === "supervisiones") {
    return <SupervisionBoard data={data} search={search} setSearch={setSearch}/>;
  }
  const rows = filter(data, search);
  if (!rows.length) return <Empty icon={section === "personal" ? UsersRound : AlertTriangle} title="Sin registros" />;
  if (section === "personal") return <div className="table-panel"><div className="data-table zonal-admin-table"><div className="data-table__head"><span>Administrador</span><span>Tienda asignada</span><span>DNI</span><span>Usuario</span><span>Estado</span><span>Acción</span></div>{rows.map((row) => <div className="data-table__row" key={row.id}><div className="person-cell"><span className="avatar">{row.nombres?.[0]}</span><div><strong>{row.nombres} {row.apellidos}</strong><small>Ingreso {formatDate(row.fecha_ingreso)}</small></div></div><span>{row.tienda_nombre||"Disponible para asignar"}</span><strong className="mono">{row.dni||"Sin DNI"}</strong><span>@{row.usuario}</span><StatusBadge value={row.estado} /><button className="button button--ghost button--small" onClick={()=>editAdministrator(row)}><Pencil size={14}/>Editar</button></div>)}</div></div>;
  if (section === "tareas") return <div className="cards-list">{rows.map((row) => <article className="task-catalog-card" key={row.id}><span className="catalog-icon"><ClipboardCheck size={18} /></span><div><strong>{row.titulo}</strong><span>{row.tiendas?.nombre} · {row.responsable} · vence {formatDate(row.fecha_limite)}</span></div><select value={row.estado} onChange={(event) => changeTask(row.id, event.target.value)}><option value="pendiente">Pendiente</option><option value="en_progreso">En progreso</option><option value="completada">Completada</option><option value="cancelada">Cancelada</option></select><StatusBadge value={row.prioridad} /></article>)}</div>;
  return <ZonalIncidents rows={rows} changeIncident={changeIncident}/>;
}

function ZonalIncidents({rows,changeIncident}) {
  const [type,setType]=useState("todos"),[scope,setScope]=useState("todos"),[origin,setOrigin]=useState("todos"),[affected,setAffected]=useState("todos"),[status,setStatus]=useState("todos");
  const filtered=rows.filter(row=>(type==="todos"||row.tipo===type)&&(scope==="todos"||row.alcance===scope)&&(origin==="todos"||String(row.tienda_origen_id)===origin)&&(affected==="todos"||String(row.tienda_afectada_id)===affected)&&(status==="todos"||row.estado===status));
  const stores=[...new Map(rows.flatMap(row=>[[row.tienda_origen_id,row.origen?.nombre],[row.tienda_afectada_id,row.afectada?.nombre]]).filter(([id])=>id).map(([id,name])=>[id,{id,name}])).values()];
  return <section className="zonal-incidents"><div className="zonal-incident-filters"><select value={type} onChange={e=>setType(e.target.value)}><option value="todos">Tipo de incidencia</option>{incidentTypes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={scope} onChange={e=>setScope(e.target.value)}><option value="todos">Alcance</option>{incidentScopes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={origin} onChange={e=>setOrigin(e.target.value)}><option value="todos">Tienda origen</option>{stores.map(store=><option key={store.id} value={store.id}>{store.name}</option>)}</select><select value={affected} onChange={e=>setAffected(e.target.value)}><option value="todos">Tienda afectada</option>{stores.map(store=><option key={store.id} value={store.id}>{store.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="todos">Estado</option><option value="abierta">Abierta</option><option value="en_seguimiento">En seguimiento</option><option value="cerrada">Cerrada</option></select></div><div className="zonal-incident-table"><div className="zonal-incident-row head"><span>Código</span><span>Fecha</span><span>Tipo</span><span>Alcance</span><span>Tienda origen</span><span>Tienda afectada</span><span>Estado</span></div>{filtered.map(row=><div className="zonal-incident-row" key={row.id}><strong>IZ-{String(row.id).padStart(4,"0")}</strong><span>{formatDate(row.fecha)}</span><span>{labelOption(incidentTypes,row.tipo)}</span><span>{labelOption(incidentScopes,row.alcance)}</span><span>{row.origen?.nombre||"—"}</span><span>{row.afectada?.nombre||"—"}</span><select value={row.estado} onChange={e=>changeIncident(row.id,e.target.value)}><option value="abierta">Abierta</option><option value="en_seguimiento">En seguimiento</option><option value="cerrada">Cerrada</option></select><p>{row.descripcion}</p></div>)}</div><small className="zonal-incident-count">Mostrando {filtered.length} de {rows.length} incidencias</small></section>;
}

function SupervisionBoard({data,search,setSearch}) {
  const [store,setStore]=useState("todos"),[admin,setAdmin]=useState("todos"),[status,setStatus]=useState("todos"),[urgency,setUrgency]=useState("todos"),[date,setDate]=useState("");
  const [selected,setSelected]=useState(null),[observation,setObservation]=useState(null),[comment,setComment]=useState(""),[result,setResult]=useState("validar"),[busy,setBusy]=useState(false);
  const rows=data.visitas.map(visit=>{const observations=data.observaciones.filter(item=>item.visita_id===visit.id);const pending=observations.filter(item=>item.estado==="en_validacion").length;const chief=visit.tiendas?.jefe;return{...visit,observations,pending,adminName:chief?`${chief.nombres} ${chief.apellidos}`:"Sin administrador",computedStatus:pending?"por_validar":observations.some(item=>item.estado!=="levantada")?"en_seguimiento":"cerrada"};});
  const filtered=rows.filter(row=>JSON.stringify(row).toLowerCase().includes(search.toLowerCase())&&(store==="todos"||String(row.tienda_id)===store)&&(admin==="todos"||row.adminName===admin)&&(status==="todos"||row.computedStatus===status)&&(!date||row.fecha===date)&&(urgency==="todos"||row.observations.some(item=>item.prioridad===urgency)));
  const stores=[...new Map(rows.map(row=>[row.tienda_id,{id:row.tienda_id,nombre:row.tiendas?.nombre}])).values()]; const admins=[...new Set(rows.map(row=>row.adminName))];
  const validate=async()=>{if(!observation)return;setBusy(true);try{await api(`/zonal/observaciones/${observation.id}/validar`,{method:"PUT",body:{resultado:result,comentario:comment}});window.location.reload();}finally{setBusy(false);}};
  const openChecklist=async visit=>{if(!visit.checklist_path)return;const {url}=await api("/zonal/supervisiones/archivo-url",{method:"POST",body:{path:visit.checklist_path,visita_id:visit.id}});window.open(url,"_blank","noopener,noreferrer");};
  return <div className="supervision-register"><div className="supervision-register-actions"><button className="button button--ghost" onClick={()=>downloadFile("/api/zonal/supervisiones/export.xlsx","supervisiones-zonales.xlsx")}><Download size={16}/>Descargar Excel</button><button className="button button--ghost" onClick={()=>window.print()}><Download size={16}/>Descargar PDF</button></div><div className="supervision-register-filters"><label><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar supervisión"/></label><select value={store} onChange={e=>setStore(e.target.value)}><option value="todos">Tienda</option>{stores.map(item=><option key={item.id} value={item.id}>{item.nombre}</option>)}</select><select value={admin} onChange={e=>setAdmin(e.target.value)}><option value="todos">Administrador</option>{admins.map(item=><option key={item} value={item}>{item}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="todos">Estado</option><option value="por_validar">Por validar</option><option value="en_seguimiento">En seguimiento</option><option value="cerrada">Cerrada</option></select><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><select value={urgency} onChange={e=>setUrgency(e.target.value)}><option value="todos">Nivel de urgencia</option><option value="baja">Baja</option><option value="media">Media</option><option value="alta">Alta</option><option value="urgente">Urgente</option></select></div><div className="supervision-register-table"><div className="supervision-register-row head"><span>Código</span><span>Tienda</span><span>Administrador</span><span>Fecha visita</span><span>Checklist físico</span><span>Observaciones</span><span>Por validar</span><span>Estado</span><span>Acción</span></div>{filtered.map(row=><div className="supervision-register-row" key={row.id}><strong>SUP-{String(row.id).padStart(4,"0")}</strong><span>{row.tiendas?.nombre||"—"}</span><span>{row.adminName}</span><span>{formatDate(row.fecha)}</span><button disabled={!row.checklist_path} onClick={()=>openChecklist(row)}>{row.checklist_path?"Descargar":"No adjunto"}</button><span>{row.observations.length}</span><span>{row.pending}</span><StatusBadge value={row.computedStatus}/><button onClick={()=>setSelected(row)}>Ver</button></div>)}</div><small>Mostrando {filtered.length} de {rows.length} supervisiones</small><p className="supervision-register-note">El checklist se realiza físicamente. El administrador digitaliza la visita y el Jefe Zonal revisa y valida los levantamientos.</p>
    <Modal open={!!selected} wide title={selected?`Supervisión SUP-${String(selected.id).padStart(4,"0")}`:"Supervisión"} subtitle={selected?`${selected.tiendas?.nombre} · Visita física ${formatDate(selected.fecha)}`:""} onClose={()=>{setSelected(null);setObservation(null);}}>{selected&&<div className="supervision-detail"><section><h3>Datos de la visita</h3><dl><div><dt>Tienda</dt><dd>{selected.tiendas?.nombre}</dd></div><div><dt>Fecha visita</dt><dd>{formatDate(selected.fecha)}</dd></div><div><dt>Administrador</dt><dd>{selected.adminName}</dd></div><div><dt>Periodo / quincena</dt><dd>{selected.periodo||"Sin registrar"}</dd></div><div><dt>Checklist físico</dt><dd><button disabled={!selected.checklist_path} onClick={()=>openChecklist(selected)}>{selected.checklist_path?"Descargar PDF":"No adjunto"}</button></dd></div><div><dt>Puntaje</dt><dd>{selected.puntaje??"—"}</dd></div></dl></section><section><h3>Observaciones</h3>{selected.observations.length?<div className="supervision-observation-table">{selected.observations.map(item=><article key={item.id}><strong>OBS-{String(item.id).padStart(4,"0")}</strong><span>{item.area_item}</span><p>{item.descripcion}</p><span className={`priority priority--${item.prioridad}`}>{item.prioridad}</span><span>{formatDate(item.fecha_limite)}</span><StatusBadge value={item.estado}/><button onClick={()=>{setObservation(item);setResult("validar");setComment("");}}>Revisar</button></article>)}</div>:<SupervisionEmpty text="La visita no tiene observaciones."/>}</section>{observation&&<section className="supervision-validation"><h3>Validación de OBS-{String(observation.id).padStart(4,"0")}</h3><div className="form-grid"><Field label="Resultado"><select value={result} onChange={e=>setResult(e.target.value)}><option value="validar">Validar y cerrar</option><option value="reabrir">Reabrir observación</option></select></Field><Field label="Comentario del Jefe Zonal"><input value={comment} onChange={e=>setComment(e.target.value)}/></Field><div className="form-actions span-2"><button className="button button--ghost" onClick={()=>setObservation(null)}>Cancelar</button><button className="button button--primary" disabled={busy} onClick={validate}>{busy?"Guardando…":result==="validar"?"Validar y cerrar":"Reabrir observación"}</button></div></div></section>}</div>}</Modal>
  </div>;
}

function SupervisionEmpty({text}){return <div className="supervision-empty"><CheckCircle2 size={25}/><strong>Todo en orden</strong><span>{text}</span></div>}

function TaskFields({ form, setForm }) { return <><Field label="Título"><input required value={form.titulo} onChange={(e) => setForm({ ...form, titulo: e.target.value })} /></Field><Field label="Responsable"><input required value={form.responsable} onChange={(e) => setForm({ ...form, responsable: e.target.value })} /></Field><Field label="Fecha de inicio"><input type="date" value={form.fecha_inicio} onChange={(e) => setForm({ ...form, fecha_inicio: e.target.value })} /></Field><Field label="Fecha límite"><input required type="date" value={form.fecha_limite} onChange={(e) => setForm({ ...form, fecha_limite: e.target.value })} /></Field><Field label="Prioridad"><select value={form.prioridad} onChange={(e) => setForm({ ...form, prioridad: e.target.value })}><option value="baja">Baja</option><option value="media">Media</option><option value="alta">Alta</option><option value="urgente">Urgente</option></select></Field><Field label="Descripción" className="span-2"><textarea rows="3" value={form.descripcion} onChange={(e) => setForm({ ...form, descripcion: e.target.value })} /></Field></>; }
function AdministratorFields({form,setForm}) { return <><Field label="Nombres *"><input required value={form.nombres} onChange={e=>setForm({...form,nombres:e.target.value})}/></Field><Field label="Apellidos *"><input required value={form.apellidos} onChange={e=>setForm({...form,apellidos:e.target.value})}/></Field><Field label="DNI *"><input required inputMode="numeric" pattern="[0-9]{8}" maxLength="8" value={form.dni} onChange={e=>setForm({...form,dni:e.target.value.replace(/\D/g,"")})}/></Field><Field label="Celular"><input inputMode="numeric" maxLength="9" value={form.telefono||""} onChange={e=>setForm({...form,telefono:e.target.value.replace(/\D/g,"")})}/></Field><Field label="Usuario *"><input required value={form.usuario} onChange={e=>setForm({...form,usuario:e.target.value.toLowerCase().replace(/\s/g,"")})}/></Field><Field label={form.id?"Nueva contraseña (opcional)":"Contraseña temporal *"}><input required={!form.id} type="password" minLength="8" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></Field><Field label="Fecha de ingreso *"><input required type="date" value={form.fecha_ingreso} onChange={e=>setForm({...form,fecha_ingreso:e.target.value})}/></Field>{form.id&&<Field label="Estado"><select value={form.estado} onChange={e=>setForm({...form,estado:e.target.value})}><option value="activo">Activo</option><option value="inactivo">Inactivo</option></select></Field>}<div className="span-2 form-hint">La asignación de tienda se gestiona desde Mis tiendas. La contraseña actual se conserva si dejas el campo vacío.</div></>; }
function IncidentFields({form,setForm,stores}) { return <><Field label="Tipo de incidencia *"><select required value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}>{incidentTypes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="Alcance *"><select required value={form.alcance} onChange={e=>setForm({...form,alcance:e.target.value})}>{incidentScopes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="Fecha de ocurrencia *"><input required type="date" value={form.fecha} onChange={e=>setForm({...form,fecha:e.target.value})}/></Field><Field label="Tienda origen"><select value={form.tienda_origen_id} onChange={e=>setForm({...form,tienda_origen_id:e.target.value})}><option value="">No aplica</option>{stores.map(store=><option key={store.id} value={store.id}>{store.nombre}</option>)}</select></Field><Field label="Tienda afectada / destino"><select value={form.tienda_afectada_id} onChange={e=>setForm({...form,tienda_afectada_id:e.target.value})}><option value="">Seleccionar</option>{stores.map(store=><option key={store.id} value={store.id}>{store.nombre}</option>)}</select></Field><Field label="Estado *"><select value={form.estado} onChange={e=>setForm({...form,estado:e.target.value})}><option value="abierta">Abierta</option><option value="en_seguimiento">En seguimiento</option><option value="cerrada">Cerrada</option></select></Field><Field label="Descripción *" className="span-2"><textarea required rows="5" value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})}/></Field><Field label="Evidencia / documento"><input type="file" accept=".pdf,image/*" onChange={e=>setForm({...form,evidencia:e.target.files?.[0]||null})}/></Field><Field label="Responsable de seguimiento"><input disabled value="Jefe Zonal"/></Field></>; }
function SupervisionFields({ form, setForm }) { return <><Field label="Fecha"><input required type="date" value={form.fecha} onChange={(e) => setForm({ ...form, fecha: e.target.value })} /></Field><Field label="Periodo"><input placeholder="Ej. Setiembre 2026" value={form.periodo} onChange={(e) => setForm({ ...form, periodo: e.target.value })} /></Field><Field label="Puntaje"><input type="number" min="0" max="100" value={form.puntaje} onChange={(e) => setForm({ ...form, puntaje: e.target.value })} /></Field><Field label="Checklist / formato"><input value={form.checklist_nombre} onChange={(e) => setForm({ ...form, checklist_nombre: e.target.value })} /></Field><Field label="Observación general" className="span-2"><textarea required rows="3" value={form.observacion_general} onChange={(e) => setForm({ ...form, observacion_general: e.target.value })} /></Field><Field label="Área del hallazgo"><input value={form.area_item} onChange={(e) => setForm({ ...form, area_item: e.target.value })} /></Field><Field label="Prioridad"><select value={form.prioridad} onChange={(e) => setForm({ ...form, prioridad: e.target.value })}><option value="baja">Baja</option><option value="media">Media</option><option value="alta">Alta</option><option value="urgente">Urgente</option></select></Field><Field label="Hallazgo" className="span-2"><textarea rows="3" value={form.hallazgo} onChange={(e) => setForm({ ...form, hallazgo: e.target.value })} /></Field><Field label="Acción correctiva"><textarea rows="3" value={form.accion_solicitada} onChange={(e) => setForm({ ...form, accion_solicitada: e.target.value })} /></Field><Field label="Fecha límite"><input type="date" value={form.fecha_limite} onChange={(e) => setForm({ ...form, fecha_limite: e.target.value })} /></Field></>; }
function Empty({ icon, title }) { return <EmptyState icon={icon} title={title} text="No hay información disponible para las tiendas de tu zona." />; }
function filter(rows, search) { const term = search.toLowerCase(); return (rows || []).filter((row) => JSON.stringify(row).toLowerCase().includes(term)); }
function blank(section) { if(section==="personal")return{nombres:"",apellidos:"",dni:"",telefono:"",usuario:"",password:"",fecha_ingreso:todayISO()};if(section==="incidencias")return{tipo:"diferencia_transferencia",alcance:"entre_tiendas",tienda_origen_id:"",tienda_afectada_id:"",fecha:todayISO(),descripcion:"",estado:"abierta",evidencia:null};return section === "tareas" ? { tienda_id: "", titulo: "", descripcion: "", responsable: "", fecha_inicio: todayISO(), fecha_limite: "", prioridad: "media" } : { tienda_id: "", fecha: todayISO(), periodo: "", puntaje: "", checklist_nombre: "", observacion_general: "", area_item: "", prioridad: "media", hallazgo: "", accion_solicitada: "", fecha_limite: "" }; }
