BEGIN;

CREATE TABLE public.requerimientos_tienda (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id BIGINT NOT NULL REFERENCES public.tiendas(id) ON DELETE CASCADE,
  requerimiento TEXT NOT NULL,
  cantidad NUMERIC(12,2) CHECK (cantidad IS NULL OR cantidad > 0),
  areas_responsables TEXT[] NOT NULL DEFAULT '{}',
  urgencia TEXT NOT NULL DEFAULT 'corto_plazo'
    CHECK (urgencia IN ('urgente','corto_plazo','mediano_plazo','largo_plazo')),
  fecha_inicio DATE NOT NULL DEFAULT CURRENT_DATE,
  fecha_fin_objetivo DATE,
  estado TEXT NOT NULL DEFAULT 'pendiente'
    CHECK (estado IN ('pendiente','en_proceso','atendido','cancelado')),
  evidencia_path TEXT,
  evidencia_nombre TEXT,
  comentario TEXT,
  creado_por BIGINT REFERENCES public.usuarios(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.requerimiento_seguimientos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requerimiento_id BIGINT NOT NULL REFERENCES public.requerimientos_tienda(id) ON DELETE CASCADE,
  usuario_id BIGINT REFERENCES public.usuarios(id) ON DELETE SET NULL,
  comentario TEXT NOT NULL,
  estado TEXT NOT NULL CHECK (estado IN ('pendiente','en_proceso','atendido','cancelado')),
  evidencia_path TEXT,
  evidencia_nombre TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX requerimientos_tienda_estado_idx
  ON public.requerimientos_tienda(tienda_id, estado, fecha_fin_objetivo);
CREATE INDEX requerimiento_seguimientos_req_idx
  ON public.requerimiento_seguimientos(requerimiento_id, created_at DESC);

ALTER TABLE public.requerimientos_tienda ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.requerimiento_seguimientos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.requerimientos_tienda, public.requerimiento_seguimientos FROM anon, authenticated;
GRANT ALL ON public.requerimientos_tienda, public.requerimiento_seguimientos TO service_role;

COMMIT;
