ALTER TABLE public.tiendas
  ADD COLUMN IF NOT EXISTS codigo text,
  ADD COLUMN IF NOT EXISTS zona text,
  ADD COLUMN IF NOT EXISTS formato text,
  ADD COLUMN IF NOT EXISTS distrito text;

CREATE UNIQUE INDEX IF NOT EXISTS tiendas_codigo_uidx ON public.tiendas (lower(codigo)) WHERE codigo IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.documentos_municipales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id bigint NOT NULL REFERENCES public.tiendas(id) ON DELETE CASCADE,
  area_responsable text NOT NULL,
  codigo text,
  tipo_documento text NOT NULL,
  frecuencia_revision text,
  fecha_emision date,
  fecha_vencimiento date,
  estado text NOT NULL DEFAULT 'vigente' CHECK (estado IN ('vigente','por_vencer','vencido','en_renovacion')),
  archivo_path text,
  archivo_nombre text,
  creado_por bigint REFERENCES public.usuarios(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.reclamaciones_tienda (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id bigint NOT NULL REFERENCES public.tiendas(id) ON DELETE CASCADE,
  codigo_hoja text NOT NULL,
  fecha date NOT NULL DEFAULT CURRENT_DATE,
  consumidor_nombre text NOT NULL, consumidor_documento text, consumidor_contacto text,
  producto_servicio text NOT NULL, monto numeric(12,2) CHECK (monto IS NULL OR monto >= 0),
  tipo text NOT NULL CHECK (tipo IN ('reclamo','queja')),
  detalle text NOT NULL, pedido_consumidor text, observaciones_proveedor text, acciones_adoptadas text,
  fecha_respuesta date, responsable text,
  estado text NOT NULL DEFAULT 'registrado' CHECK (estado IN ('registrado','en_atencion','respondido','cerrado')),
  archivo_path text, archivo_nombre text,
  creado_por bigint REFERENCES public.usuarios(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tienda_id, codigo_hoja)
);

CREATE TABLE IF NOT EXISTS public.acciones_tienda (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id bigint NOT NULL REFERENCES public.tiendas(id) ON DELETE CASCADE,
  fecha date NOT NULL, tipo text NOT NULL, responsable text NOT NULL, accion text NOT NULL,
  estado text NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente','en_progreso','completada','cancelada')),
  objetivo text, observacion text, evidencia_path text, evidencia_nombre text,
  creado_por bigint REFERENCES public.usuarios(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.bitacora_tienda (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id bigint NOT NULL REFERENCES public.tiendas(id) ON DELETE CASCADE,
  fecha date NOT NULL, venta_dia numeric(14,2) NOT NULL DEFAULT 0 CHECK (venta_dia >= 0),
  trafico integer NOT NULL DEFAULT 0 CHECK (trafico >= 0), categoria text NOT NULL,
  evento text, descripcion text, evidencia_path text, evidencia_nombre text,
  creado_por bigint REFERENCES public.usuarios(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tienda_id, fecha)
);

CREATE TABLE IF NOT EXISTS public.visitas_zonales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id bigint NOT NULL REFERENCES public.tiendas(id) ON DELETE CASCADE,
  jefe_zonal_id bigint REFERENCES public.usuarios(id) ON DELETE SET NULL,
  fecha date NOT NULL, periodo text, puntaje numeric(5,2) CHECK (puntaje IS NULL OR (puntaje >= 0 AND puntaje <= 100)),
  checklist_path text, checklist_nombre text, observacion_general text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.observaciones_zonales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visita_id bigint REFERENCES public.visitas_zonales(id) ON DELETE SET NULL,
  tienda_id bigint NOT NULL REFERENCES public.tiendas(id) ON DELETE CASCADE,
  area_item text NOT NULL, prioridad text NOT NULL CHECK (prioridad IN ('baja','media','alta','urgente')),
  fecha_limite date, descripcion text NOT NULL, accion_solicitada text, evidencia_inicial_path text, evidencia_inicial_nombre text,
  estado text NOT NULL DEFAULT 'abierta' CHECK (estado IN ('abierta','en_proceso','en_validacion','levantada','rechazada')),
  accion_realizada text, evidencia_cierre_path text, evidencia_cierre_nombre text,
  soporte_requerido boolean NOT NULL DEFAULT false, comentario text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mejoras_continuas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id bigint NOT NULL REFERENCES public.tiendas(id) ON DELETE CASCADE,
  fecha date NOT NULL, seccion text NOT NULL, area text NOT NULL, responsable text NOT NULL,
  que_mejoro text NOT NULL, como_se_hizo text NOT NULL,
  foto_antes_path text, foto_antes_nombre text, foto_despues_path text, foto_despues_nombre text,
  estado text NOT NULL DEFAULT 'registrada' CHECK (estado IN ('registrada','en_progreso','completada')),
  resultado_beneficio text, creado_por bigint REFERENCES public.usuarios(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS documentos_municipales_tienda_fecha_idx ON public.documentos_municipales(tienda_id, fecha_vencimiento);
CREATE INDEX IF NOT EXISTS reclamaciones_tienda_estado_idx ON public.reclamaciones_tienda(tienda_id, estado);
CREATE INDEX IF NOT EXISTS acciones_tienda_fecha_idx ON public.acciones_tienda(tienda_id, fecha);
CREATE INDEX IF NOT EXISTS bitacora_tienda_fecha_idx ON public.bitacora_tienda(tienda_id, fecha DESC);
CREATE INDEX IF NOT EXISTS visitas_zonales_tienda_fecha_idx ON public.visitas_zonales(tienda_id, fecha DESC);
CREATE INDEX IF NOT EXISTS observaciones_zonales_tienda_estado_idx ON public.observaciones_zonales(tienda_id, estado);
CREATE INDEX IF NOT EXISTS mejoras_continuas_tienda_fecha_idx ON public.mejoras_continuas(tienda_id, fecha DESC);

ALTER TABLE public.documentos_municipales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reclamaciones_tienda ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.acciones_tienda ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bitacora_tienda ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visitas_zonales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.observaciones_zonales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mejoras_continuas ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.documentos_municipales, public.reclamaciones_tienda, public.acciones_tienda,
  public.bitacora_tienda, public.visitas_zonales, public.observaciones_zonales, public.mejoras_continuas FROM anon, authenticated;
GRANT ALL ON public.documentos_municipales, public.reclamaciones_tienda, public.acciones_tienda,
  public.bitacora_tienda, public.visitas_zonales, public.observaciones_zonales, public.mejoras_continuas TO service_role;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('mi-tienda', 'mi-tienda', false, 5242880, ARRAY['application/pdf','image/jpeg','image/png','image/webp'])
ON CONFLICT (id) DO UPDATE SET public = false, file_size_limit = EXCLUDED.file_size_limit, allowed_mime_types = EXCLUDED.allowed_mime_types;
