CREATE TABLE IF NOT EXISTS public.programaciones_asistencia_zonal (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  nombre text NOT NULL CHECK (char_length(nombre) BETWEEN 2 AND 100),
  asunto text NOT NULL CHECK (char_length(asunto) BETWEEN 2 AND 150),
  hora time NOT NULL,
  activo boolean NOT NULL DEFAULT true,
  tienda_id integer REFERENCES public.tiendas(id) ON DELETE RESTRICT,
  destinatarios text[] NOT NULL CHECK (cardinality(destinatarios) BETWEEN 1 AND 20),
  proximo_envio timestamptz NOT NULL,
  ultimo_envio timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS programaciones_asistencia_pendientes_idx ON public.programaciones_asistencia_zonal(proximo_envio) WHERE activo;

CREATE TABLE IF NOT EXISTS public.envios_asistencia_zonal (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  programacion_id bigint REFERENCES public.programaciones_asistencia_zonal(id) ON DELETE SET NULL,
  usuario_id integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  nombre text NOT NULL,
  fecha date NOT NULL,
  tipo text NOT NULL CHECK (tipo IN ('manual', 'automatico')),
  estado text NOT NULL DEFAULT 'enviando' CHECK (estado IN ('enviando', 'enviado', 'error')),
  destinatarios text[] NOT NULL,
  asistentes integer NOT NULL DEFAULT 0,
  faltas integer NOT NULL DEFAULT 0,
  sin_registro integer NOT NULL DEFAULT 0,
  intentos integer NOT NULL DEFAULT 1,
  detalle text,
  created_at timestamptz NOT NULL DEFAULT now(),
  enviado_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS envios_asistencia_unico_automatico_idx ON public.envios_asistencia_zonal(programacion_id,fecha) WHERE tipo = 'automatico';
CREATE INDEX IF NOT EXISTS envios_asistencia_historial_idx ON public.envios_asistencia_zonal(usuario_id,created_at DESC);

ALTER TABLE public.programaciones_asistencia_zonal ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.envios_asistencia_zonal ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.programaciones_asistencia_zonal, public.envios_asistencia_zonal FROM anon, authenticated;
GRANT ALL ON public.programaciones_asistencia_zonal, public.envios_asistencia_zonal TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.programaciones_asistencia_zonal_id_seq, public.envios_asistencia_zonal_id_seq TO service_role;
