BEGIN;

CREATE TABLE public.tareas_zonales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jefe_zonal_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  tienda_id BIGINT NOT NULL REFERENCES public.tiendas(id) ON DELETE CASCADE,
  titulo TEXT NOT NULL,
  descripcion TEXT,
  responsable TEXT NOT NULL,
  fecha_inicio DATE NOT NULL DEFAULT CURRENT_DATE,
  fecha_limite DATE NOT NULL,
  prioridad TEXT NOT NULL DEFAULT 'media' CHECK (prioridad IN ('baja','media','alta','urgente')),
  estado TEXT NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente','en_progreso','completada','vencida','cancelada')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX tareas_zonales_jefe_fecha_idx ON public.tareas_zonales(jefe_zonal_id, fecha_limite);
CREATE INDEX tareas_zonales_tienda_estado_idx ON public.tareas_zonales(tienda_id, estado);
ALTER TABLE public.tareas_zonales ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.tareas_zonales FROM anon, authenticated;
GRANT ALL ON public.tareas_zonales TO service_role;

COMMIT;
