BEGIN;

ALTER TABLE public.usuarios
  ADD COLUMN IF NOT EXISTS zonal_creador_id BIGINT REFERENCES public.usuarios(id) ON DELETE SET NULL;

ALTER TABLE public.usuarios DROP CONSTRAINT IF EXISTS usuarios_tienda_rol_check;
ALTER TABLE public.usuarios
  ADD CONSTRAINT usuarios_tienda_rol_check CHECK (
    (rol IN ('gerencia_general','gerente_comercial','coach','jefe_zonal') AND tienda_id IS NULL)
    OR (rol = 'jefe_tienda')
    OR (rol IN ('asistente_tienda','jefe_seguridad','jefe_area','seguridad','caja','almacenero','vendedor','asistente','trabajador') AND tienda_id IS NOT NULL)
  );

CREATE INDEX IF NOT EXISTS usuarios_zonal_creador_idx ON public.usuarios(zonal_creador_id, rol);

CREATE TABLE public.incidencias_zonales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  jefe_zonal_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE RESTRICT,
  tipo TEXT NOT NULL CHECK (tipo IN ('diferencia_transferencia','coordinacion_tiendas','apoyo_tiendas','logistica_externa','proveedor','infraestructura_externa','otro')),
  alcance TEXT NOT NULL CHECK (alcance IN ('entre_tiendas','externa_tienda','varias_tiendas')),
  tienda_origen_id BIGINT REFERENCES public.tiendas(id) ON DELETE SET NULL,
  tienda_afectada_id BIGINT REFERENCES public.tiendas(id) ON DELETE SET NULL,
  fecha DATE NOT NULL,
  descripcion TEXT NOT NULL,
  estado TEXT NOT NULL DEFAULT 'abierta' CHECK (estado IN ('abierta','en_seguimiento','cerrada')),
  responsable_seguimiento TEXT NOT NULL,
  evidencia_path TEXT,
  evidencia_nombre TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (tienda_origen_id IS NOT NULL OR tienda_afectada_id IS NOT NULL)
);

CREATE INDEX incidencias_zonales_jefe_fecha_idx ON public.incidencias_zonales(jefe_zonal_id, fecha DESC);
ALTER TABLE public.incidencias_zonales ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.incidencias_zonales FROM anon, authenticated;
GRANT ALL ON public.incidencias_zonales TO service_role;

COMMIT;
