BEGIN;

ALTER TABLE public.tiendas
  ADD COLUMN IF NOT EXISTS alquiler_mensual NUMERIC(12,2)
  CHECK (alquiler_mensual IS NULL OR alquiler_mensual >= 0);

ALTER TABLE public.documentos_municipales
  ADD COLUMN IF NOT EXISTS responsables TEXT[] NOT NULL DEFAULT '{}';

UPDATE public.documentos_municipales
SET responsables = ARRAY[area_responsable]
WHERE cardinality(responsables) = 0 AND area_responsable IS NOT NULL;

CREATE TABLE public.apoyos_seguridad (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT NOT NULL UNIQUE REFERENCES public.usuarios(id) ON DELETE CASCADE,
  tienda_id BIGINT NOT NULL REFERENCES public.tiendas(id) ON DELETE CASCADE,
  dni VARCHAR(8) NOT NULL UNIQUE CHECK (dni ~ '^[0-9]{8}$'),
  foto_referencia_path TEXT NOT NULL,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NOT NULL CHECK (fecha_fin >= fecha_inicio),
  motivo TEXT,
  activo BOOLEAN NOT NULL DEFAULT true,
  creado_por BIGINT REFERENCES public.usuarios(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.apoyo_seguridad_accesos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  apoyo_id BIGINT NOT NULL REFERENCES public.apoyos_seguridad(id) ON DELETE CASCADE,
  foto_rostro_path TEXT NOT NULL,
  ip TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX apoyos_seguridad_tienda_vigencia_idx
  ON public.apoyos_seguridad(tienda_id, activo, fecha_inicio, fecha_fin);
CREATE INDEX apoyo_seguridad_accesos_apoyo_idx
  ON public.apoyo_seguridad_accesos(apoyo_id, created_at DESC);

ALTER TABLE public.apoyos_seguridad ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.apoyo_seguridad_accesos ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.apoyos_seguridad, public.apoyo_seguridad_accesos FROM anon, authenticated;
GRANT ALL ON public.apoyos_seguridad, public.apoyo_seguridad_accesos TO service_role;

COMMIT;
